// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-tile.cuh"

DECL_FATTN_TILE_CASE(128, 128);

#if defined(GGML_USE_HIP) && defined(GGML_HIP_QUANT_KV_FATTN_TILE)
DECL_FATTN_TILE_QUANT_CASE(128, 128, GGML_TYPE_Q8_0);
DECL_FATTN_TILE_QUANT_CASE(128, 128, GGML_TYPE_Q4_0);
#endif
