#include "halofpx-context-store-bootstrap-anchor.h"

#include <algorithm>
#include <cstring>
#include <limits>
#include <new>
#include <utility>
#include <vector>

namespace halofpx {
void (*context_store_bootstrap_anchor_synthetic_coordinator::post_positive_test_hook_)() = nullptr;
bool context_store_bootstrap_anchor_synthetic_backend::fail_history_allocation_test_ = false;
namespace {

using bytes = std::vector<uint8_t>;
constexpr char object_domain[] = "halofpx.object.v1";
constexpr std::array<uint8_t, 8> object_magic = { 0x48,0x41,0x4c,0x4f,0x4f,0x42,0x4a,0x01 };
constexpr uint64_t hash_limit = 70ull * 1024ull * 1024ull;

bool zero(const context_store_format_digest & d) noexcept { uint8_t v=0;for(auto b:d)v|=b;return v==0; }
bool same(const context_store_format_digest&a,const context_store_format_digest&b)noexcept{uint8_t v=0;for(size_t i=0;i<a.size();++i)v|=static_cast<uint8_t>(a[i]^b[i]);return v==0;}
bool exact(const uint8_t*a,const uint8_t*b,size_t n)noexcept{if((!a||!b)&&n)return false;uint8_t v=0;for(size_t i=0;i<n;++i)v|=static_cast<uint8_t>(a[i]^b[i]);return v==0;}
bool registered(const context_store_registered_id&id)noexcept{if(!id.size||id.size>context_store_registered_id_max_bytes)return false;for(size_t i=0;i<id.size;++i)if(id.bytes[i]<=0||static_cast<unsigned char>(id.bytes[i])>=0x80)return false;return true;}
void put(bytes&b,const void*p,size_t n){const auto*q=static_cast<const uint8_t*>(p);b.insert(b.end(),q,q+n);}
void u64(bytes&b,uint64_t v){for(int s=56;s>=0;s-=8)b.push_back(static_cast<uint8_t>(v>>s));}
void u8(bytes&b,uint8_t v){b.push_back(v);}
void domain(bytes&b,const char*s){put(b,s,std::strlen(s)+1);}
bool sha(const bytes&b,context_store_format_digest&d)noexcept{return context_store_sha256_bounded(b.data(),b.size(),hash_limit,d);}

bool exact_anchor(const context_store_authenticated_anchor&a,const context_store_authenticated_anchor&b)noexcept{
    return a.authenticated()&&b.authenticated()&&a.envelope_size()==b.envelope_size()&&a.envelope_digest()&&b.envelope_digest()&&
        same(*a.envelope_digest(),*b.envelope_digest())&&exact(a.envelope_data(),b.envelope_data(),a.envelope_size());
}

bool exact_id(const context_store_registered_id&a,const context_store_registered_id&b)noexcept{
    return a.size==b.size&&exact(reinterpret_cast<const uint8_t*>(a.bytes.data()),reinterpret_cast<const uint8_t*>(b.bytes.data()),a.size);
}

bool frame_valid(const uint8_t*f,size_t n,const context_store_object_reference&r)noexcept{
    if(!f||!n||n!=r.frame_bytes)return false;size_t p=0;auto take=[&](size_t z,const uint8_t*&q){if(p>n||z>n-p)return false;q=f+p;p+=z;return true;};const uint8_t*q=nullptr;
    if(!take(object_magic.size(),q)||!exact(q,object_magic.data(),object_magic.size())||!take(2,q))return false;
    const uint16_t dl=static_cast<uint16_t>((q[0]<<8)|q[1]);if(dl!=sizeof(object_domain)-1||!take(dl,q)||!exact(q,reinterpret_cast<const uint8_t*>(object_domain),dl)||!take(2,q))return false;
    const uint16_t tl=static_cast<uint16_t>((q[0]<<8)|q[1]);if(!tl||tl!=r.stream_type.size||tl>context_store_registered_id_max_bytes||!take(tl,q)||!exact(q,reinterpret_cast<const uint8_t*>(r.stream_type.bytes.data()),tl))return false;
    if(!take(8,q))return false;uint64_t payload=0;for(size_t i=0;i<8;++i)payload=(payload<<8)|q[i];if(payload!=n-p)return false;
    context_store_format_digest d{};return context_store_sha256_bounded(f,n,n,d)&&same(d,r.object_id);
}

bool policy_commitment(const context_store_bootstrap_anchor_synthetic_policy&p,context_store_format_digest&out){
    bytes b;domain(b,"halofpx.bootstrap-anchor-root-policy.v1");put(b,p.anchor_root_identity.data(),32);put(b,p.material_root_identity.data(),32);put(b,p.registry_root_identity.data(),32);put(b,p.store_uuid.data(),16);put(b,p.namespace_id.data(),32);put(b,p.checkpoint_lineage_id.data(),32);u64(b,p.policy_epoch);u64(b,p.manifest_key_generation);u64(b,p.writer_authority_epoch);u64(b,p.anchor_authentication_key_id.size);put(b,p.anchor_authentication_key_id.bytes.data(),p.anchor_authentication_key_id.size);u64(b,p.anchor_authentication_key_generation);u64(b,p.durability_policy_id.size);put(b,p.durability_policy_id.bytes.data(),p.durability_policy_id.size);u64(b,p.maximum_anchor_envelope_bytes);return sha(b,out);
}

bool material_close(const context_store_bootstrap_material_synthetic_proof&m,context_store_format_digest&out){
    if(!m.valid()||!m.material_root_identity()||!m.registry_root_identity()||!m.material_attempt_id()||!m.operation_commitment()||!m.source_set_commitment()||!m.material_set_commitment()||!m.proposed_anchor()||!m.proposed_anchor()->body())return false;
    bytes b;domain(b,"halofpx.bootstrap-material-durable-close.v1");put(b,m.material_root_identity()->data(),32);put(b,m.registry_root_identity()->data(),32);put(b,m.material_attempt_id()->data(),32);put(b,m.operation_commitment()->data(),32);put(b,m.source_set_commitment()->data(),32);put(b,m.material_set_commitment()->data(),32);put(b,m.proposed_anchor()->body()->selected_manifest_digest.data(),32);u8(b,1);return sha(b,out);
}

bool material_source(const context_store_bootstrap_material_synthetic_proof&m,context_store_format_digest&out){
    if(!m.valid()||!m.material_root_identity()||!m.registry_root_identity()||!m.material_attempt_id()||!m.root_policy_commitment()||!m.authority_source_commitment()||!m.source_set_commitment()||!m.material_set_commitment()||!m.operation_commitment()||!m.proposed_anchor()||!m.durable_close_confirmation())return false;
    const char*tag=nullptr;size_t tag_n=0;if(m.classified_outcome()==context_store_bootstrap_material_synthetic_backend_outcome::prepared_backend_claim){tag="material-prepared-v1";tag_n=20;}else if(m.classified_outcome()==context_store_bootstrap_material_synthetic_backend_outcome::already_same_backend_claim){tag="material-already-same-v1";tag_n=24;}else return false;
    bytes b;domain(b,"halofpx.bootstrap-anchor-material-source.v1");u64(b,tag_n);put(b,tag,tag_n);put(b,m.material_root_identity()->data(),32);put(b,m.registry_root_identity()->data(),32);put(b,m.material_attempt_id()->data(),32);put(b,m.root_policy_commitment()->data(),32);put(b,m.authority_source_commitment()->data(),32);put(b,m.source_set_commitment()->data(),32);put(b,m.material_set_commitment()->data(),32);put(b,m.operation_commitment()->data(),32);put(b,m.proposed_anchor()->body()->selected_manifest_digest.data(),32);u64(b,m.manifest_envelope_size());put(b,m.manifest_envelope_data(),m.manifest_envelope_size());u64(b,m.observed_frame_count());for(size_t i=0;i<m.observed_frame_count();++i){u64(b,i);u64(b,m.observed_frame_size(i));put(b,m.observed_frame_data(i),m.observed_frame_size(i));}u64(b,m.proposed_anchor()->envelope_size());put(b,m.proposed_anchor()->envelope_data(),m.proposed_anchor()->envelope_size());put(b,m.durable_close_confirmation()->data(),32);return sha(b,out);
}

bool source_valid(const context_store_bootstrap_material_synthetic_proof&m,const context_store_bootstrap_anchor_synthetic_policy&p)noexcept{
    try{
        if(!m.valid()||!m.fixed_policy()||!m.material_root_identity()||!m.registry_root_identity()||!m.proposed_anchor()||!m.proposed_anchor()->authenticated()||
            !same(*m.material_root_identity(),p.material_root_identity)||!same(*m.registry_root_identity(),p.registry_root_identity)||m.proposed_anchor()->envelope_size()==0||m.proposed_anchor()->envelope_size()>p.maximum_anchor_envelope_bytes)return false;
        const auto*mp=m.fixed_policy();const auto*a=m.proposed_anchor();const auto*ab=a->body();const auto*k=a->authentication_key_id();if(!ab||!k||!a->envelope_digest())return false;
        if(mp->store_uuid!=p.store_uuid||!same(mp->namespace_id,p.namespace_id)||!same(mp->checkpoint_lineage_id,p.checkpoint_lineage_id)||mp->policy_epoch!=p.policy_epoch||mp->manifest_key_generation!=p.manifest_key_generation||mp->writer_authority_epoch!=p.writer_authority_epoch||ab->store_uuid!=p.store_uuid||!same(ab->namespace_id,p.namespace_id)||!same(ab->checkpoint_lineage_id,p.checkpoint_lineage_id)||ab->policy_epoch!=p.policy_epoch||ab->manifest_key_generation!=p.manifest_key_generation||ab->authority_epoch!=p.writer_authority_epoch||ab->generation!=1||ab->has_predecessor||!exact_id(*k,p.anchor_authentication_key_id)||a->authentication_key_generation()!=p.anchor_authentication_key_generation)return false;
        context_store_format_digest md{},close{};if(!m.manifest_envelope_data()||!m.manifest_envelope_size()||!context_store_manifest_digest_v1(m.manifest_envelope_data(),m.manifest_envelope_size(),md)||!same(md,ab->selected_manifest_digest)||!material_close(m,close)||!same(close,*m.durable_close_confirmation()))return false;
        const auto parsed=context_store_parse_manifest_v1(m.manifest_envelope_data(),m.manifest_envelope_size());if(parsed.status!=context_store_manifest_parse_status::structural_only||parsed.manifest.object_count!=m.descriptor_count()||m.observed_frame_count()!=m.descriptor_count())return false;
        for(size_t i=0;i<m.descriptor_count();++i){const auto*d=m.descriptor(i);if(!d||d->object_id!=parsed.manifest.object_references[i].object_id||d->frame_bytes!=parsed.manifest.object_references[i].frame_bytes||!exact_id(d->stream_type,parsed.manifest.object_references[i].stream_type)||!frame_valid(m.observed_frame_data(i),m.observed_frame_size(i),*d))return false;}
        return true;
    }catch(...){return false;}
}

bool create_commitment(const context_store_bootstrap_anchor_synthetic_operation&o,context_store_format_digest&out){bytes b;domain(b,"halofpx.bootstrap-anchor-create.v1");put(b,o.anchor_root_identity.data(),32);put(b,o.material_root_identity.data(),32);put(b,o.registry_root_identity.data(),32);put(b,o.anchor_attempt_id.data(),32);put(b,o.root_policy_commitment.data(),32);put(b,o.material_source_commitment.data(),32);put(b,o.selected_manifest_digest.data(),32);u64(b,o.proposed_anchor.envelope_size());put(b,o.proposed_anchor.envelope_data(),o.proposed_anchor.envelope_size());return sha(b,out);}
bool witness_digest(const uint8_t*p,size_t n,context_store_format_digest&out){bytes b;domain(b,"halofpx.protected-anchor-head-witness.v1");u64(b,n);put(b,p,n);return sha(b,out);}
bool create_close(const context_store_bootstrap_anchor_synthetic_operation&o,const uint8_t*p,size_t n,context_store_format_digest&out){context_store_format_digest w{};if(!witness_digest(p,n,w))return false;bytes b;domain(b,"halofpx.bootstrap-anchor-durable-close.v1");put(b,o.anchor_root_identity.data(),32);put(b,o.material_root_identity.data(),32);put(b,o.registry_root_identity.data(),32);put(b,o.anchor_attempt_id.data(),32);put(b,o.create_operation_commitment.data(),32);put(b,o.material_source_commitment.data(),32);put(b,o.proposed_anchor_digest.data(),32);put(b,w.data(),32);u8(b,1);return sha(b,out);}

bool operation_echo(const context_store_bootstrap_anchor_synthetic_witness&w,const context_store_bootstrap_anchor_synthetic_operation&o)noexcept{return w.anchor_attempt_id==o.anchor_attempt_id&&same(w.anchor_root_identity,o.anchor_root_identity)&&same(w.material_root_identity,o.material_root_identity)&&same(w.registry_root_identity,o.registry_root_identity)&&same(w.root_policy_commitment,o.root_policy_commitment)&&same(w.material_source_commitment,o.material_source_commitment)&&same(w.create_operation_commitment,o.create_operation_commitment)&&same(w.selected_manifest_digest,o.selected_manifest_digest);}

bool reconciliation_commitment(const context_store_bootstrap_anchor_synthetic_reconciliation_operation&o,context_store_format_digest&out){bytes b;domain(b,"halofpx.bootstrap-anchor-reconciliation.v1");put(b,o.anchor_root_identity.data(),32);put(b,o.material_root_identity.data(),32);put(b,o.registry_root_identity.data(),32);put(b,o.reconciliation_attempt_id.data(),32);put(b,o.original_anchor_attempt_id.data(),32);put(b,o.original_create_operation_commitment.data(),32);u8(b,o.original_phase);put(b,o.root_policy_commitment.data(),32);put(b,o.material_source_commitment.data(),32);u64(b,o.proposed_anchor.envelope_size());put(b,o.proposed_anchor.envelope_data(),o.proposed_anchor.envelope_size());return sha(b,out);}
bool reconciliation_echo(const context_store_bootstrap_anchor_synthetic_reconciliation_operation&a,const context_store_bootstrap_anchor_synthetic_reconciliation_operation&b)noexcept{return a.reconciliation_attempt_id==b.reconciliation_attempt_id&&a.original_anchor_attempt_id==b.original_anchor_attempt_id&&same(a.anchor_root_identity,b.anchor_root_identity)&&same(a.material_root_identity,b.material_root_identity)&&same(a.registry_root_identity,b.registry_root_identity)&&same(a.reconciliation_commitment,b.reconciliation_commitment)&&same(a.original_create_operation_commitment,b.original_create_operation_commitment)&&same(a.root_policy_commitment,b.root_policy_commitment)&&same(a.material_source_commitment,b.material_source_commitment)&&a.original_phase==b.original_phase&&exact_anchor(a.proposed_anchor,b.proposed_anchor);}
bool fence_close(const context_store_bootstrap_anchor_synthetic_reconciliation_operation&o,const uint8_t*p,size_t n,uint8_t cls,context_store_format_digest&f,context_store_format_digest&c){context_store_format_digest w{};if(!witness_digest(p,n,w))return false;bytes b;domain(b,"halofpx.bootstrap-anchor-reconciliation-fence.v1");put(b,o.anchor_root_identity.data(),32);put(b,o.reconciliation_attempt_id.data(),32);put(b,o.reconciliation_commitment.data(),32);put(b,o.original_anchor_attempt_id.data(),32);put(b,o.original_create_operation_commitment.data(),32);u8(b,o.original_phase);put(b,w.data(),32);u8(b,cls);u8(b,1);if(!sha(b,f))return false;b.clear();domain(b,"halofpx.bootstrap-anchor-reconciliation-durable-close.v1");put(b,o.anchor_root_identity.data(),32);put(b,o.reconciliation_attempt_id.data(),32);put(b,o.reconciliation_commitment.data(),32);put(b,o.original_anchor_attempt_id.data(),32);put(b,o.original_create_operation_commitment.data(),32);u8(b,o.original_phase);put(b,o.material_source_commitment.data(),32);put(b,o.proposed_anchor.envelope_digest()->data(),32);put(b,w.data(),32);put(b,f.data(),32);u8(b,1);return sha(b,c);}

bool policy_valid(const context_store_bootstrap_anchor_synthetic_policy&p)noexcept{return !zero(p.anchor_root_identity)&&!zero(p.material_root_identity)&&!zero(p.registry_root_identity)&&!same(p.anchor_root_identity,p.material_root_identity)&&!same(p.anchor_root_identity,p.registry_root_identity)&&!same(p.material_root_identity,p.registry_root_identity)&&registered(p.anchor_authentication_key_id)&&p.anchor_authentication_key_generation&&registered(p.durability_policy_id)&&p.maximum_anchor_envelope_bytes==context_store_anchor_max_bytes;}

} // namespace

context_store_bootstrap_anchor_synthetic_uncertain_handle::context_store_bootstrap_anchor_synthetic_uncertain_handle(context_store_bootstrap_anchor_synthetic_uncertain_handle&&o)noexcept{*this=std::move(o);}
context_store_bootstrap_anchor_synthetic_uncertain_handle&context_store_bootstrap_anchor_synthetic_uncertain_handle::operator=(context_store_bootstrap_anchor_synthetic_uncertain_handle&&o)noexcept{if(this!=&o){valid_=o.valid_;owner_=o.owner_;original_attempt_=o.original_attempt_;original_operation_=o.original_operation_;o.valid_=false;o.owner_=nullptr;o.original_attempt_={};o.original_operation_={};}return *this;}
context_store_bootstrap_anchor_synthetic_proof::context_store_bootstrap_anchor_synthetic_proof(context_store_bootstrap_anchor_synthetic_proof&&o)noexcept{*this=std::move(o);}
context_store_bootstrap_anchor_synthetic_proof&context_store_bootstrap_anchor_synthetic_proof::operator=(context_store_bootstrap_anchor_synthetic_proof&&o)noexcept{if(this!=&o){valid_=o.valid_;recovered_=o.recovered_;original_phase_=o.original_phase_;material_=std::move(o.material_);policy_=o.policy_;anchor_attempt_=o.anchor_attempt_;reconciliation_attempt_=o.reconciliation_attempt_;root_policy_=o.root_policy_;material_source_=o.material_source_;create_operation_=o.create_operation_;close_=o.close_;reconciliation_commitment_=o.reconciliation_commitment_;fence_confirmation_=o.fence_confirmation_;observed_=o.observed_;observed_size_=o.observed_size_;o.valid_=false;o.recovered_=false;o.original_phase_=3;o.anchor_attempt_={};o.reconciliation_attempt_={};o.observed_size_=0;}return *this;}

context_store_bootstrap_anchor_synthetic_backend::context_store_bootstrap_anchor_synthetic_backend(const context_store_bootstrap_anchor_synthetic_policy&p)noexcept:policy_(p),terminal_attempts_(fail_history_allocation_test_?nullptr:new(std::nothrow) std::array<context_store_bootstrap_anchor_synthetic_id,maximum_terminal_attempts_>{}){valid_=policy_valid(p);}
context_store_bootstrap_anchor_synthetic_backend::~context_store_bootstrap_anchor_synthetic_backend()=default;
void context_store_bootstrap_anchor_synthetic_backend::record_conclusive_pre_create_inspection(const context_store_bootstrap_anchor_synthetic_id&a)noexcept{if(pending_state_==pending_state::create_active&&pending_operation_.anchor_attempt_id==a){if(original_phase_!=2)original_phase_=1;}else if(original_phase_!=2)original_phase_=3;}
void context_store_bootstrap_anchor_synthetic_backend::record_create_linearized(const context_store_bootstrap_anchor_synthetic_id&a)noexcept{if(pending_state_==pending_state::create_active&&pending_operation_.anchor_attempt_id==a&&(original_phase_==1||original_phase_==2))original_phase_=2;else original_phase_=3;}

context_store_bootstrap_anchor_synthetic_status context_store_bootstrap_anchor_synthetic_backend::execute_create(context_store_bootstrap_material_synthetic_proof&&source,const context_store_bootstrap_anchor_synthetic_operation&o,context_store_bootstrap_anchor_synthetic_witness&w)noexcept{
    using S=context_store_bootstrap_anchor_synthetic_status;using O=context_store_bootstrap_anchor_synthetic_backend_outcome;std::lock_guard<std::mutex>lock(mutex_);
    if(quarantined()||pending_state_!=pending_state::none)return quarantined()?S::anchor_root_quarantined:S::writer_busy;
    for(size_t i=0;i<terminal_attempt_count_;++i)if((*terminal_attempts_)[i]==o.anchor_attempt_id)return S::attempt_replayed;
    if(terminal_attempt_count_==maximum_terminal_attempts_)return S::history_exhausted;
    (*terminal_attempts_)[terminal_attempt_count_++]=o.anchor_attempt_id;pending_operation_=o;pending_material_=std::move(source);pending_state_=pending_state::create_active;original_phase_=3;
    try{
        context_store_format_digest pc{},ms{},oc{};if(!source_valid(pending_material_,policy_)||!policy_commitment(policy_,pc)||!material_source(pending_material_,ms)||!create_commitment(o,oc)||!same(pc,o.root_policy_commitment)||!same(ms,o.material_source_commitment)||!same(oc,o.create_operation_commitment)){quarantined_.store(true,std::memory_order_release);pending_state_=pending_state::uncertain;return S::visibility_uncertain;}
        w=inspect_create_if_absent_synchronize_and_durable_close(o);
        if(w.outcome==O::created_backend_claim){context_store_format_digest close{};const bool ok=original_phase_==2&&operation_echo(w,o)&&w.observed_current_size==o.proposed_anchor.envelope_size()&&w.observed_current_size>0&&w.observed_current_size<=policy_.maximum_anchor_envelope_bytes&&exact(w.observed_current.data(),o.proposed_anchor.envelope_data(),w.observed_current_size)&&create_close(o,w.observed_current.data(),w.observed_current_size,close)&&same(close,w.durable_close_confirmation);if(!ok){quarantined_.store(true,std::memory_order_release);pending_state_=pending_state::uncertain;return S::visibility_uncertain;}pending_state_=pending_state::positive_ready;return S::created_backend_claim;}
        auto terminal=[&](S s){pending_material_={};pending_operation_={};pending_state_=pending_state::none;original_phase_=3;return s;};
        if(w.outcome==O::already_present_no_create){if(original_phase_!=1||!operation_echo(w,o)||w.observed_current_size!=o.proposed_anchor.envelope_size()||!exact(w.observed_current.data(),o.proposed_anchor.envelope_data(),w.observed_current_size)){quarantined_.store(true,std::memory_order_release);pending_state_=pending_state::uncertain;return S::visibility_uncertain;}return terminal(S::already_present_no_create);}
        if(w.outcome==O::anchor_conflict){if(original_phase_!=1||!operation_echo(w,o)||!w.observed_current_size||w.observed_current_size>policy_.maximum_anchor_envelope_bytes||(w.observed_current_size==o.proposed_anchor.envelope_size()&&exact(w.observed_current.data(),o.proposed_anchor.envelope_data(),w.observed_current_size))){quarantined_.store(true,std::memory_order_release);pending_state_=pending_state::uncertain;return S::visibility_uncertain;}return terminal(S::anchor_conflict);}
        if(original_phase_!=1){quarantined_.store(true,std::memory_order_release);pending_state_=pending_state::uncertain;return S::visibility_uncertain;}
        if(w.outcome==O::writer_busy)return terminal(S::writer_busy);if(w.outcome==O::read_only)return terminal(S::read_only);if(w.outcome==O::storage_error)return terminal(S::storage_error);if(w.outcome==O::synchronization_error)return terminal(S::synchronization_error);if(w.outcome==O::definitely_aborted)return terminal(S::definitely_aborted);
    }catch(...){ }
    quarantined_.store(true,std::memory_order_release);pending_state_=pending_state::uncertain;return S::visibility_uncertain;
}

bool context_store_bootstrap_anchor_synthetic_backend::claim_positive(const context_store_bootstrap_anchor_synthetic_operation&o,const context_store_bootstrap_anchor_synthetic_witness&w,context_store_bootstrap_anchor_synthetic_proof&proof)noexcept{std::lock_guard<std::mutex>lock(mutex_);if(pending_state_!=pending_state::positive_ready||pending_operation_.anchor_attempt_id!=o.anchor_attempt_id)return false;proof.valid_=true;proof.original_phase_=2;proof.material_=std::move(pending_material_);proof.policy_=policy_;proof.anchor_attempt_=o.anchor_attempt_id;proof.root_policy_=o.root_policy_commitment;proof.material_source_=o.material_source_commitment;proof.create_operation_=o.create_operation_commitment;proof.observed_=w.observed_current;proof.observed_size_=w.observed_current_size;proof.close_=w.durable_close_confirmation;pending_operation_={};pending_state_=pending_state::none;original_phase_=3;return true;}
void context_store_bootstrap_anchor_synthetic_backend::make_uncertain_handle(context_store_bootstrap_anchor_synthetic_uncertain_handle&h)noexcept{std::lock_guard<std::mutex>lock(mutex_);if(pending_state_==pending_state::uncertain||pending_state_==pending_state::positive_ready){pending_state_=pending_state::uncertain;quarantined_.store(true,std::memory_order_release);h.valid_=true;h.owner_=this;h.original_attempt_=pending_operation_.anchor_attempt_id;h.original_operation_=pending_operation_.create_operation_commitment;}}

context_store_bootstrap_anchor_synthetic_result context_store_bootstrap_anchor_synthetic_coordinator::create(context_store_bootstrap_material_synthetic_proof&&source,const context_store_bootstrap_anchor_synthetic_request&r)noexcept{
    context_store_bootstrap_material_synthetic_proof owned=std::move(source);context_store_bootstrap_anchor_synthetic_result result;
    try{
        if(!owned.valid()){result.status=context_store_bootstrap_anchor_synthetic_status::invalid_source;return result;}
        if(!backend_.valid()||zero(r.anchor_attempt_id)||!source_valid(owned,backend_.policy())){result.status=context_store_bootstrap_anchor_synthetic_status::invalid_request;return result;}
        if(!backend_.terminal_attempts_){result.status=context_store_bootstrap_anchor_synthetic_status::resource_exhausted;return result;}
        context_store_bootstrap_anchor_synthetic_operation o;o.anchor_attempt_id=r.anchor_attempt_id;o.anchor_root_identity=backend_.policy().anchor_root_identity;o.material_root_identity=backend_.policy().material_root_identity;o.registry_root_identity=backend_.policy().registry_root_identity;o.proposed_anchor=*owned.proposed_anchor();o.selected_manifest_digest=o.proposed_anchor.body()->selected_manifest_digest;o.proposed_anchor_digest=*o.proposed_anchor.envelope_digest();
        if(!policy_commitment(backend_.policy(),o.root_policy_commitment)||!material_source(owned,o.material_source_commitment)||!create_commitment(o,o.create_operation_commitment)){result.status=context_store_bootstrap_anchor_synthetic_status::resource_exhausted;return result;}
        context_store_bootstrap_anchor_synthetic_witness w;result.status=backend_.execute_create(std::move(owned),o,w);
        if(result.status==context_store_bootstrap_anchor_synthetic_status::created_backend_claim){if(post_positive_test_hook_)post_positive_test_hook_();if(!backend_.claim_positive(o,w,result.proof)){backend_.make_uncertain_handle(result.uncertain_handle);result.status=context_store_bootstrap_anchor_synthetic_status::visibility_uncertain;}}
        else if(result.status==context_store_bootstrap_anchor_synthetic_status::visibility_uncertain)backend_.make_uncertain_handle(result.uncertain_handle);
        return result;
    }catch(...){backend_.make_uncertain_handle(result.uncertain_handle);result.status=result.uncertain_handle.valid()?context_store_bootstrap_anchor_synthetic_status::visibility_uncertain:context_store_bootstrap_anchor_synthetic_status::resource_exhausted;return result;}
}

context_store_bootstrap_anchor_synthetic_reconciliation_status context_store_bootstrap_anchor_synthetic_backend::execute_reconciliation(context_store_bootstrap_anchor_synthetic_uncertain_handle&&h,const context_store_bootstrap_anchor_synthetic_id&rid,context_store_bootstrap_anchor_synthetic_proof&proof)noexcept{
    using S=context_store_bootstrap_anchor_synthetic_reconciliation_status;using O=context_store_bootstrap_anchor_synthetic_reconciliation_backend_outcome;std::lock_guard<std::mutex>lock(mutex_);
    if(!h.valid_||h.owner_!=this||pending_state_!=pending_state::uncertain||h.original_attempt_!=pending_operation_.anchor_attempt_id||!same(h.original_operation_,pending_operation_.create_operation_commitment))return S::not_reconcilable;
    if(reconciliation_registered_)return reconciliation_attempt_==rid?S::attempt_replayed:S::not_reconcilable;reconciliation_registered_=true;reconciliation_attempt_=rid;
    context_store_bootstrap_anchor_synthetic_reconciliation_operation o;o.reconciliation_attempt_id=rid;o.original_anchor_attempt_id=pending_operation_.anchor_attempt_id;o.anchor_root_identity=pending_operation_.anchor_root_identity;o.material_root_identity=pending_operation_.material_root_identity;o.registry_root_identity=pending_operation_.registry_root_identity;o.original_create_operation_commitment=pending_operation_.create_operation_commitment;o.root_policy_commitment=pending_operation_.root_policy_commitment;o.material_source_commitment=pending_operation_.material_source_commitment;o.original_phase=original_phase_;o.proposed_anchor=pending_operation_.proposed_anchor;if(!reconciliation_commitment(o,o.reconciliation_commitment))return S::visibility_uncertain;
    try{auto w=fence_original_observe_current_synchronize_and_durable_close(o);const bool echo=reconciliation_echo(w.echo,o);uint8_t cls=0;if(w.outcome==O::exact_present)cls=1;else if(w.outcome==O::absent)cls=2;else if(w.outcome==O::other_present)cls=3;else return S::visibility_uncertain;context_store_format_digest f{},c{};const bool shape=(cls==2?w.observed_current_size==0:(w.observed_current_size>0&&w.observed_current_size<=policy_.maximum_anchor_envelope_bytes));if(!echo||w.classification!=cls||!shape||!fence_close(o,w.observed_current.data(),w.observed_current_size,cls,f,c)||!same(f,w.fence_confirmation)||!same(c,w.durable_close_confirmation)){return S::visibility_uncertain;}const bool is_exact=w.observed_current_size==o.proposed_anchor.envelope_size()&&exact(w.observed_current.data(),o.proposed_anchor.envelope_data(),w.observed_current_size);auto terminal=[&](S s){pending_material_={};pending_operation_={};pending_state_=pending_state::reconciled;return s;};if(cls==1){if(!is_exact)return S::visibility_uncertain;if(original_phase_==2){proof.valid_=true;proof.recovered_=true;proof.original_phase_=original_phase_;proof.material_=std::move(pending_material_);proof.policy_=policy_;proof.anchor_attempt_=o.original_anchor_attempt_id;proof.reconciliation_attempt_=rid;proof.root_policy_=o.root_policy_commitment;proof.material_source_=o.material_source_commitment;proof.create_operation_=o.original_create_operation_commitment;proof.reconciliation_commitment_=o.reconciliation_commitment;proof.fence_confirmation_=w.fence_confirmation;proof.close_=w.durable_close_confirmation;proof.observed_=w.observed_current;proof.observed_size_=w.observed_current_size;pending_operation_={};pending_state_=pending_state::reconciled;return S::created_same_recovered_backend_claim;}if(original_phase_==1)return terminal(S::already_present_fenced_no_retry);return S::visibility_uncertain;}if(cls==2){if(original_phase_==1)return terminal(S::definitely_not_created_fenced_no_retry);return S::visibility_uncertain;}if(is_exact)return S::visibility_uncertain;return terminal(S::anchor_conflict);}catch(...){return S::visibility_uncertain;}
}

context_store_bootstrap_anchor_synthetic_reconciliation_result context_store_bootstrap_anchor_synthetic_reconciliation_coordinator::reconcile(context_store_bootstrap_anchor_synthetic_uncertain_handle&&source,const context_store_bootstrap_anchor_synthetic_reconciliation_request&r)noexcept{context_store_bootstrap_anchor_synthetic_uncertain_handle h=std::move(source);context_store_bootstrap_anchor_synthetic_reconciliation_result result;if(!h.valid_){result.status=context_store_bootstrap_anchor_synthetic_reconciliation_status::invalid_handle;return result;}if(zero(r.reconciliation_attempt_id)){result.status=context_store_bootstrap_anchor_synthetic_reconciliation_status::invalid_request;return result;}if(h.owner_!=&backend_){result.status=context_store_bootstrap_anchor_synthetic_reconciliation_status::not_reconcilable;return result;}result.status=backend_.execute_reconciliation(std::move(h),r.reconciliation_attempt_id,result.proof);return result;}

const char*context_store_bootstrap_anchor_synthetic_status_name(context_store_bootstrap_anchor_synthetic_status s)noexcept{using S=context_store_bootstrap_anchor_synthetic_status;switch(s){case S::created_backend_claim:return"created-backend-claim";case S::already_present_no_create:return"already-present-no-create";case S::anchor_conflict:return"anchor-conflict";case S::invalid_source:return"invalid-source";case S::invalid_request:return"invalid-request";case S::writer_busy:return"writer-busy";case S::read_only:return"read-only";case S::storage_error:return"storage-error";case S::synchronization_error:return"synchronization-error";case S::definitely_aborted:return"definitely-aborted";case S::attempt_replayed:return"attempt-replayed";case S::history_exhausted:return"history-exhausted";case S::anchor_root_quarantined:return"anchor-root-quarantined";case S::resource_exhausted:return"resource-exhausted";case S::visibility_uncertain:return"visibility-uncertain";}return"unknown";}
const char*context_store_bootstrap_anchor_synthetic_reconciliation_status_name(context_store_bootstrap_anchor_synthetic_reconciliation_status s)noexcept{using S=context_store_bootstrap_anchor_synthetic_reconciliation_status;switch(s){case S::created_same_recovered_backend_claim:return"created-same-recovered-backend-claim";case S::already_present_fenced_no_retry:return"already-present-fenced-no-retry";case S::definitely_not_created_fenced_no_retry:return"definitely-not-created-fenced-no-retry";case S::anchor_conflict:return"anchor-conflict";case S::invalid_handle:return"invalid-handle";case S::invalid_request:return"invalid-request";case S::attempt_replayed:return"attempt-replayed";case S::not_reconcilable:return"not-reconcilable";case S::anchor_root_quarantined:return"anchor-root-quarantined";case S::visibility_uncertain:return"visibility-uncertain";}return"unknown";}

} // namespace halofpx
