#include "halofpx-context-store-protected-registry.h"

#include <algorithm>
#include <array>
#include <climits>
#include <cstring>

namespace halofpx { namespace {

constexpr char key_domain[] = "halofpx.registry-snapshot-key.v1";
constexpr char auth_domain[] = "halofpx.registry-snapshot-auth.v1";
constexpr char digest_domain[] = "halofpx.registry-snapshot.v1";
constexpr char continuity_domain[] = "halofpx.registry-key-continuity.v1";
constexpr uint64_t format_major = 1, format_minor = 0, registry_kind_bootstrap_authorization = 0;
constexpr uint64_t algorithm_hmac_sha256 = 1;

struct writer {
    uint8_t * data; size_t capacity, size = 0;
    bool raw(const void * p,size_t n) noexcept { if((!p&&n)||!data||n>capacity-size)return false;std::memcpy(data+size,p,n);size+=n;return true; }
    bool head(uint8_t m,uint64_t v) noexcept { if(v<24){uint8_t b=uint8_t(m<<5|v);return raw(&b,1);} if(v<=UINT8_MAX){uint8_t b[2]={uint8_t(m<<5|24),uint8_t(v)};return raw(b,2);} if(v<=UINT16_MAX){uint8_t b[3]={uint8_t(m<<5|25),uint8_t(v>>8),uint8_t(v)};return raw(b,3);} if(v<=UINT32_MAX){uint8_t b[5]={uint8_t(m<<5|26)};for(size_t i=0;i<4;++i)b[4-i]=uint8_t(v>>(8*i));return raw(b,5);}uint8_t b[9]={uint8_t(m<<5|27)};for(size_t i=0;i<8;++i)b[8-i]=uint8_t(v>>(8*i));return raw(b,9); }
    bool u64(uint64_t v) noexcept{return head(0,v);} bool bstr(const void*p,size_t n)noexcept{return head(2,n)&&raw(p,n);} bool tstr(const void*p,size_t n)noexcept{return head(3,n)&&raw(p,n);}
};
struct reader {
    const uint8_t * data; size_t size, offset=0;
    bool head(uint8_t m,uint64_t&v)noexcept{if(offset>=size)return false;uint8_t f=data[offset++];if((f>>5)!=m)return false;uint8_t a=f&31;if(a<24){v=a;return true;}size_t n=a==24?1:a==25?2:a==26?4:a==27?8:0;if(!n||n>size-offset)return false;v=0;for(size_t i=0;i<n;++i)v=(v<<8)|data[offset++];return !((n==1&&v<24)||(n==2&&v<=UINT8_MAX)||(n==4&&v<=UINT16_MAX)||(n==8&&v<=UINT32_MAX));}
    bool exact(uint64_t v)noexcept{uint64_t x=0;return head(0,x)&&x==v;} bool u64(uint64_t&v)noexcept{return head(0,v);}
    bool bytes(uint8_t m,const uint8_t*&p,size_t&n)noexcept{uint64_t z=0;if(!head(m,z)||z>size-offset)return false;p=data+offset;n=size_t(z);offset+=n;return true;}
};
void wipe(void*p,size_t n)noexcept{volatile uint8_t*b=static_cast<volatile uint8_t*>(p);while(n--)*b++=0;}
template<size_t N>bool nonzero(const std::array<uint8_t,N>&v)noexcept{uint8_t x=0;for(auto b:v)x|=b;return x!=0;}
bool valid_id(const context_store_registered_id&id)noexcept{if(!id.size||id.size>context_store_registered_id_max_bytes)return false;for(size_t i=0;i<id.size;++i){const auto value=static_cast<uint8_t>(id.bytes[i]);if(!value||value>0x7f)return false;}return true;}
bool same_id(const context_store_registered_id&a,const context_store_registered_id&b)noexcept{if(a.size!=b.size)return false;volatile uint8_t x=0;for(size_t i=0;i<a.size;++i)x=uint8_t(x|(a.bytes[i]^b.bytes[i]));return x==0;}
bool same_digest(const context_store_format_digest&a,const context_store_format_digest&b)noexcept{volatile uint8_t x=0;for(size_t i=0;i<a.size();++i)x=uint8_t(x|(a[i]^b[i]));return x==0;}
bool valid_body(const context_store_protected_registry_body&b)noexcept{return valid_id(b.registry_id)&&b.registry_epoch&&nonzero(b.authority_base_scope_commitment)&&nonzero(b.policy_commitment)&&b.last_consumed_sequence!=UINT64_MAX;}
bool valid_key(const context_store_protected_registry_key_record&k)noexcept{return valid_id(k.key_id)&&k.generation&&k.master_key.data&&k.master_key.size&&k.master_key.size<=context_store_master_key_max_bytes;}
bool body_encode(const context_store_protected_registry_body&b,uint8_t*out,size_t cap,size_t&used)noexcept{writer w{out,cap};bool ok=w.head(5,8)&&w.u64(0)&&w.u64(format_major)&&w.u64(1)&&w.u64(format_minor)&&w.u64(2)&&w.u64(registry_kind_bootstrap_authorization)&&w.u64(3)&&w.tstr(b.registry_id.bytes.data(),b.registry_id.size)&&w.u64(4)&&w.u64(b.registry_epoch)&&w.u64(5)&&w.bstr(b.authority_base_scope_commitment.data(),32)&&w.u64(6)&&w.bstr(b.policy_commitment.data(),32)&&w.u64(7)&&w.u64(b.last_consumed_sequence);used=w.size;return ok;}
bool parse_id(reader&r,context_store_registered_id&v)noexcept{const uint8_t*p;size_t n;if(!r.bytes(3,p,n)||!n||n>context_store_registered_id_max_bytes)return false;v.size=uint8_t(n);std::copy_n(p,n,v.bytes.begin());return valid_id(v);}
bool parse_digest(reader&r,context_store_format_digest&v)noexcept{const uint8_t*p;size_t n;if(!r.bytes(2,p,n)||n!=v.size())return false;std::copy_n(p,n,v.begin());return true;}
bool body_parse(reader&r,context_store_protected_registry_body&b)noexcept{uint64_t n=0;return r.head(5,n)&&n==8&&r.exact(0)&&r.exact(format_major)&&r.exact(1)&&r.exact(format_minor)&&r.exact(2)&&r.exact(registry_kind_bootstrap_authorization)&&r.exact(3)&&parse_id(r,b.registry_id)&&r.exact(4)&&r.u64(b.registry_epoch)&&r.exact(5)&&parse_digest(r,b.authority_base_scope_commitment)&&r.exact(6)&&parse_digest(r,b.policy_commitment)&&r.exact(7)&&r.u64(b.last_consumed_sequence)&&valid_body(b);}
bool derive(const context_store_protected_registry_key_record&k,context_store_format_digest&out)noexcept{std::array<uint8_t,256>m{};writer w{m.data(),m.size()};bool ok=w.raw(key_domain,sizeof(key_domain))&&w.tstr(k.key_id.bytes.data(),k.key_id.size)&&w.u64(k.generation)&&context_store_hmac_sha256(k.master_key.data,k.master_key.size,m.data(),w.size,out);wipe(m.data(),m.size());return ok;}
bool tag(const context_store_protected_registry_key_record&k,const uint8_t*p,size_t n,context_store_format_digest&out)noexcept{std::array<uint8_t,context_store_protected_registry_max_bytes+64>m{};context_store_format_digest dk{};writer w{m.data(),m.size()};bool ok=derive(k,dk)&&w.raw(auth_domain,sizeof(auth_domain))&&w.raw(p,n)&&context_store_hmac_sha256(dk.data(),dk.size(),m.data(),w.size,out);wipe(dk.data(),dk.size());wipe(m.data(),m.size());return ok;}
bool digest(const uint8_t*p,size_t n,context_store_format_digest&out)noexcept{std::array<uint8_t,context_store_protected_registry_max_bytes+64>m{};writer w{m.data(),m.size()};bool ok=w.raw(digest_domain,sizeof(digest_domain))&&w.raw(p,n)&&context_store_sha256_bounded(m.data(),w.size,m.size(),out);wipe(m.data(),m.size());return ok;}
bool binding(const context_store_protected_registry_key_record&k,const context_store_format_digest&e,context_store_format_digest&out)noexcept{context_store_format_digest dk{};std::array<uint8_t,96>m{};writer w{m.data(),m.size()};bool ok=derive(k,dk)&&w.raw(digest_domain,sizeof(digest_domain))&&w.raw(e.data(),e.size())&&context_store_hmac_sha256(dk.data(),dk.size(),m.data(),w.size,out);wipe(dk.data(),dk.size());wipe(m.data(),m.size());return ok;}
bool continuity(const context_store_protected_registry_key_record&k,context_store_format_digest&out)noexcept{std::array<uint8_t,256>m{};writer w{m.data(),m.size()};bool ok=w.raw(continuity_domain,sizeof(continuity_domain))&&w.tstr(k.key_id.bytes.data(),k.key_id.size)&&w.u64(k.generation)&&context_store_hmac_sha256(k.master_key.data,k.master_key.size,m.data(),w.size,out);wipe(m.data(),m.size());return ok;}
}

void context_store_protected_registry_result::set_authenticated(const context_store_protected_registry_body&b,const context_store_protected_registry_key_record&k,const context_store_format_digest&e,const context_store_format_digest&a,const context_store_format_digest&c,const uint8_t*envelope,size_t envelope_size)noexcept{carrier_.body_=b;carrier_.key_id_=k.key_id;carrier_.key_generation_=k.generation;carrier_.envelope_digest_=e;carrier_.authority_binding_=a;carrier_.key_continuity_commitment_=c;carrier_.envelope_size_=envelope_size;std::copy_n(envelope,envelope_size,carrier_.envelope_.begin());carrier_.valid_=true;status=context_store_protected_registry_status::authenticated_unadmitted;}

context_store_protected_registry_result context_store_encode_protected_registry_v1(const context_store_protected_registry_body&b,const context_store_protected_registry_key_record&k,uint8_t*out,size_t cap)noexcept{context_store_protected_registry_result r;if(!valid_body(b)||!valid_key(k)||k.disposition!=context_store_key_disposition::active||!out){r.status=context_store_protected_registry_status::invalid_policy;return r;}std::array<uint8_t,512>bb{},ai{};size_t bn=0;context_store_format_digest t{},d{},a{},c{};writer w{ai.data(),ai.size()};bool ok=body_encode(b,bb.data(),bb.size(),bn)&&w.head(5,4)&&w.u64(0)&&w.raw(bb.data(),bn)&&w.u64(1)&&w.tstr(k.key_id.bytes.data(),k.key_id.size)&&w.u64(2)&&w.u64(algorithm_hmac_sha256)&&w.u64(3)&&w.u64(k.generation)&&tag(k,ai.data(),w.size,t);writer e{out,std::min(cap,context_store_protected_registry_max_bytes)};bool encoded=ok&&e.head(5,2)&&e.u64(0)&&e.raw(ai.data(),w.size)&&e.u64(1)&&e.bstr(t.data(),t.size());ok=encoded&&digest(out,e.size,d)&&binding(k,d,a)&&continuity(k,c);wipe(bb.data(),bb.size());wipe(ai.data(),ai.size());wipe(t.data(),t.size());if(!ok){r.status=encoded?context_store_protected_registry_status::invalid_policy:context_store_protected_registry_status::output_too_small;return r;}r.encoded_size=e.size;r.set_authenticated(b,k,d,a,c,out,e.size);wipe(d.data(),d.size());wipe(a.data(),a.size());wipe(c.data(),c.size());return r;}

context_store_protected_registry_result context_store_verify_protected_registry_v1(const uint8_t*data,size_t size,const context_store_protected_registry_key_record&k)noexcept{context_store_protected_registry_result out;if(!data||!size||size>context_store_protected_registry_max_bytes)return out;if(!valid_key(k)){out.status=context_store_protected_registry_status::invalid_policy;return out;}reader r{data,size};uint64_t n=0,alg=0,gen=0;const uint8_t*idp,*tp;size_t idn=0,tn=0;if(!r.head(5,n)||n!=2||!r.exact(0))return out;size_t ao=r.offset;if(!r.head(5,n)||n!=4||!r.exact(0))return out;context_store_protected_registry_body b;if(!body_parse(r,b)||!r.exact(1)||!r.bytes(3,idp,idn)||!r.exact(2)||!r.u64(alg)||!r.exact(3)||!r.u64(gen)||alg!=algorithm_hmac_sha256)return out;size_t an=r.offset-ao;if(!r.exact(1)||!r.bytes(2,tp,tn)||r.offset!=size||tn!=32)return out;context_store_registered_id id;if(!idn||idn>context_store_registered_id_max_bytes)return out;id.size=uint8_t(idn);std::copy_n(idp,idn,id.bytes.begin());if(!valid_id(id))return out;if(!same_id(id,k.key_id)){out.status=context_store_protected_registry_status::unknown_key;return out;}if(k.disposition==context_store_key_disposition::revoked){out.status=context_store_protected_registry_status::revoked_key;return out;}if(k.disposition==context_store_key_disposition::read_disabled){out.status=context_store_protected_registry_status::read_disabled_key;return out;}if(k.disposition!=context_store_key_disposition::active){out.status=context_store_protected_registry_status::invalid_policy;return out;}if(gen!=k.generation){out.status=context_store_protected_registry_status::key_generation_mismatch;return out;}context_store_format_digest expected{},provided{},d{},a{},c{};std::copy_n(tp,32,provided.begin());if(!tag(k,data+ao,an,expected)||!same_digest(expected,provided)){out.status=context_store_protected_registry_status::authentication_failed;wipe(expected.data(),32);wipe(provided.data(),32);return out;}bool ok=digest(data,size,d)&&binding(k,d,a)&&continuity(k,c);wipe(expected.data(),32);wipe(provided.data(),32);if(!ok){out.status=context_store_protected_registry_status::invalid_policy;return out;}out.encoded_size=size;out.set_authenticated(b,k,d,a,c,data,size);wipe(d.data(),32);wipe(a.data(),32);wipe(c.data(),32);return out;}

const char*context_store_protected_registry_status_name(context_store_protected_registry_status s)noexcept{switch(s){case context_store_protected_registry_status::authenticated_unadmitted:return "authenticated-unadmitted";case context_store_protected_registry_status::structural_rejection:return "structural-rejection";case context_store_protected_registry_status::output_too_small:return "output-too-small";case context_store_protected_registry_status::invalid_policy:return "invalid-policy";case context_store_protected_registry_status::unknown_key:return "unknown-key";case context_store_protected_registry_status::revoked_key:return "revoked-key";case context_store_protected_registry_status::read_disabled_key:return "read-disabled-key";case context_store_protected_registry_status::key_generation_mismatch:return "key-generation-mismatch";case context_store_protected_registry_status::authentication_failed:return "authentication-failed";}return "unknown";}
} // namespace halofpx
