#include "halofpx-context-store-protected-registry-successor.h"

#include <algorithm>
#include <array>
#include <climits>
#include <cstring>

namespace halofpx { namespace {
constexpr char key_domain[]="halofpx.registry-successor-key.v1";
constexpr char auth_domain[]="halofpx.registry-successor-auth.v1";
constexpr char digest_domain[]="halofpx.registry-successor.v1";
constexpr char continuity_domain[]="halofpx.registry-key-continuity.v1";
struct writer{uint8_t*d;size_t c,n=0;bool raw(const void*p,size_t z)noexcept{if((!p&&z)||!d||z>c-n)return false;std::memcpy(d+n,p,z);n+=z;return true;}bool head(uint8_t m,uint64_t v)noexcept{if(v<24){uint8_t b=uint8_t(m<<5|v);return raw(&b,1);}if(v<=UINT8_MAX){uint8_t b[2]={uint8_t(m<<5|24),uint8_t(v)};return raw(b,2);}if(v<=UINT16_MAX){uint8_t b[3]={uint8_t(m<<5|25),uint8_t(v>>8),uint8_t(v)};return raw(b,3);}if(v<=UINT32_MAX){uint8_t b[5]={uint8_t(m<<5|26)};for(size_t i=0;i<4;++i)b[4-i]=uint8_t(v>>(8*i));return raw(b,5);}uint8_t b[9]={uint8_t(m<<5|27)};for(size_t i=0;i<8;++i)b[8-i]=uint8_t(v>>(8*i));return raw(b,9);}bool u(uint64_t v)noexcept{return head(0,v);}bool bs(const void*p,size_t z)noexcept{return head(2,z)&&raw(p,z);}bool ts(const void*p,size_t z)noexcept{return head(3,z)&&raw(p,z);}};
struct reader{const uint8_t*d;size_t n,o=0;bool head(uint8_t m,uint64_t&v)noexcept{if(o>=n)return false;uint8_t f=d[o++];if(f>>5!=m)return false;uint8_t a=f&31;if(a<24){v=a;return true;}size_t z=a==24?1:a==25?2:a==26?4:a==27?8:0;if(!z||z>n-o)return false;v=0;for(size_t i=0;i<z;++i)v=v<<8|d[o++];return !((z==1&&v<24)||(z==2&&v<=255)||(z==4&&v<=65535)||(z==8&&v<=UINT32_MAX));}bool ex(uint64_t x)noexcept{uint64_t v;return head(0,v)&&v==x;}bool u(uint64_t&v)noexcept{return head(0,v);}bool bytes(uint8_t m,const uint8_t*&p,size_t&z)noexcept{uint64_t v;if(!head(m,v)||v>n-o)return false;p=d+o;z=size_t(v);o+=z;return true;}};
void wipe(void*p,size_t n)noexcept{volatile uint8_t*b=(volatile uint8_t*)p;while(n--)*b++=0;}
template<size_t N>bool nz(const std::array<uint8_t,N>&a)noexcept{uint8_t v=0;for(auto x:a)v|=x;return v;}
bool idok(const context_store_registered_id&i)noexcept{if(!i.size||i.size>context_store_registered_id_max_bytes)return false;for(size_t n=0;n<i.size;++n){auto x=(uint8_t)i.bytes[n];if(!x||x>127)return false;}return true;}
bool eqid(const context_store_registered_id&a,const context_store_registered_id&b)noexcept{return a.size==b.size&&std::equal(a.bytes.begin(),a.bytes.begin()+a.size,b.bytes.begin());}
bool eqd(const context_store_format_digest&a,const context_store_format_digest&b)noexcept{uint8_t v=0;for(size_t i=0;i<32;++i)v|=a[i]^b[i];return !v;}
bool keyok(const context_store_protected_registry_key_record&k)noexcept{return idok(k.key_id)&&k.generation&&k.master_key.data&&k.master_key.size&&k.master_key.size<=context_store_master_key_max_bytes;}
bool bodyok(const context_store_protected_registry_successor_body&b)noexcept{return idok(b.registry_id)&&b.registry_epoch&&nz(b.authority_base_scope_commitment)&&nz(b.policy_commitment)&&b.consumed_authorization_high_water&&b.receipt.authorization_sequence==b.consumed_authorization_high_water&&nz(b.predecessor_snapshot_envelope_digest)&&nz(b.receipt.command_id)&&nz(b.receipt.authorization_token_digest)&&nz(b.receipt.plan_commitment)&&nz(b.receipt.selected_manifest_digest)&&nz(b.receipt.proposed_anchor_envelope_digest);}
bool pd(reader&r,context_store_format_digest&v)noexcept{const uint8_t*p;size_t n;if(!r.bytes(2,p,n)||n!=32)return false;std::copy_n(p,32,v.begin());return true;}bool pid(reader&r,context_store_registered_id&i)noexcept{const uint8_t*p;size_t n;if(!r.bytes(3,p,n)||!n||n>128)return false;i.size=(uint8_t)n;std::copy_n(p,n,i.bytes.begin());return idok(i);}
bool receipt_enc(const context_store_bootstrap_consumption_receipt&x,writer&w)noexcept{return w.head(5,6)&&w.u(0)&&w.u(x.authorization_sequence)&&w.u(1)&&w.bs(x.command_id.data(),32)&&w.u(2)&&w.bs(x.authorization_token_digest.data(),32)&&w.u(3)&&w.bs(x.plan_commitment.data(),32)&&w.u(4)&&w.bs(x.selected_manifest_digest.data(),32)&&w.u(5)&&w.bs(x.proposed_anchor_envelope_digest.data(),32);}
bool body_enc(const context_store_protected_registry_successor_body&b,writer&w)noexcept{return w.head(5,10)&&w.u(0)&&w.u(2)&&w.u(1)&&w.u(0)&&w.u(2)&&w.u(0)&&w.u(3)&&w.ts(b.registry_id.bytes.data(),b.registry_id.size)&&w.u(4)&&w.u(b.registry_epoch)&&w.u(5)&&w.bs(b.authority_base_scope_commitment.data(),32)&&w.u(6)&&w.bs(b.policy_commitment.data(),32)&&w.u(7)&&w.u(b.consumed_authorization_high_water)&&w.u(8)&&w.bs(b.predecessor_snapshot_envelope_digest.data(),32)&&w.u(9)&&receipt_enc(b.receipt,w);}
bool receipt_parse(reader&r,context_store_bootstrap_consumption_receipt&x)noexcept{uint64_t n;return r.head(5,n)&&n==6&&r.ex(0)&&r.u(x.authorization_sequence)&&r.ex(1)&&pd(r,x.command_id)&&r.ex(2)&&pd(r,x.authorization_token_digest)&&r.ex(3)&&pd(r,x.plan_commitment)&&r.ex(4)&&pd(r,x.selected_manifest_digest)&&r.ex(5)&&pd(r,x.proposed_anchor_envelope_digest);}
bool body_parse(reader&r,context_store_protected_registry_successor_body&b)noexcept{uint64_t n;return r.head(5,n)&&n==10&&r.ex(0)&&r.ex(2)&&r.ex(1)&&r.ex(0)&&r.ex(2)&&r.ex(0)&&r.ex(3)&&pid(r,b.registry_id)&&r.ex(4)&&r.u(b.registry_epoch)&&r.ex(5)&&pd(r,b.authority_base_scope_commitment)&&r.ex(6)&&pd(r,b.policy_commitment)&&r.ex(7)&&r.u(b.consumed_authorization_high_water)&&r.ex(8)&&pd(r,b.predecessor_snapshot_envelope_digest)&&r.ex(9)&&receipt_parse(r,b.receipt)&&bodyok(b);}
bool continuity(const context_store_protected_registry_key_record&k,context_store_format_digest&o)noexcept{std::array<uint8_t,256>m{};writer w{m.data(),m.size()};bool ok=w.raw(continuity_domain,sizeof(continuity_domain))&&w.ts(k.key_id.bytes.data(),k.key_id.size)&&w.u(k.generation)&&context_store_hmac_sha256(k.master_key.data,k.master_key.size,m.data(),w.n,o);wipe(m.data(),m.size());return ok;}
bool derive(const context_store_protected_registry_key_record&k,context_store_format_digest&o)noexcept{std::array<uint8_t,256>m{};writer w{m.data(),m.size()};bool ok=w.raw(key_domain,sizeof(key_domain))&&w.ts(k.key_id.bytes.data(),k.key_id.size)&&w.u(k.generation)&&context_store_hmac_sha256(k.master_key.data,k.master_key.size,m.data(),w.n,o);wipe(m.data(),m.size());return ok;}
bool tag(const context_store_protected_registry_key_record&k,const uint8_t*p,size_t n,context_store_format_digest&o)noexcept{std::array<uint8_t,1100>m{};context_store_format_digest dk{};writer w{m.data(),m.size()};bool ok=derive(k,dk)&&w.raw(auth_domain,sizeof(auth_domain))&&w.raw(p,n)&&context_store_hmac_sha256(dk.data(),32,m.data(),w.n,o);wipe(dk.data(),32);wipe(m.data(),m.size());return ok;}
bool digest(const uint8_t*p,size_t n,context_store_format_digest&o)noexcept{std::array<uint8_t,1100>m{};writer w{m.data(),m.size()};bool ok=w.raw(digest_domain,sizeof(digest_domain))&&w.raw(p,n)&&context_store_sha256_bounded(m.data(),w.n,m.size(),o);wipe(m.data(),m.size());return ok;}
bool binding(const context_store_protected_registry_key_record&k,const context_store_format_digest&d,context_store_format_digest&o)noexcept{context_store_format_digest dk{};std::array<uint8_t,96>m{};writer w{m.data(),m.size()};bool ok=derive(k,dk)&&w.raw(digest_domain,sizeof(digest_domain))&&w.raw(d.data(),32)&&context_store_hmac_sha256(dk.data(),32,m.data(),w.n,o);wipe(dk.data(),32);wipe(m.data(),m.size());return ok;}
} // namespace

void context_store_protected_registry_successor_result::set_authenticated(const context_store_protected_registry_successor_body&b,const context_store_protected_registry_key_record&k,const context_store_format_digest&d,const context_store_format_digest&a,const context_store_format_digest&c,const uint8_t*p,size_t n)noexcept{carrier_.body_=b;carrier_.key_id_=k.key_id;carrier_.key_generation_=k.generation;carrier_.envelope_digest_=d;carrier_.authority_binding_=a;carrier_.key_continuity_commitment_=c;carrier_.envelope_size_=n;std::copy_n(p,n,carrier_.envelope_.begin());carrier_.valid_=true;status=context_store_protected_registry_successor_status::authenticated_unadmitted;}
context_store_protected_registry_successor_result context_store_encode_protected_registry_successor_v1(const context_store_protected_registry_successor_body&b,const context_store_protected_registry_key_record&k,uint8_t*out,size_t cap)noexcept{context_store_protected_registry_successor_result r;if(!bodyok(b)||!keyok(k)||k.disposition!=context_store_key_disposition::active||!out){r.status=context_store_protected_registry_successor_status::invalid_policy;return r;}std::array<uint8_t,768>body{},ai{};writer bw{body.data(),body.size()};context_store_format_digest t{},d{},a{},c{};bool ok=body_enc(b,bw);writer aw{ai.data(),ai.size()};ok=ok&&aw.head(5,4)&&aw.u(0)&&aw.raw(body.data(),bw.n)&&aw.u(1)&&aw.ts(k.key_id.bytes.data(),k.key_id.size)&&aw.u(2)&&aw.u(1)&&aw.u(3)&&aw.u(k.generation)&&tag(k,ai.data(),aw.n,t);writer ew{out,std::min(cap,context_store_protected_registry_successor_max_bytes)};bool encoded=ok&&ew.head(5,2)&&ew.u(0)&&ew.raw(ai.data(),aw.n)&&ew.u(1)&&ew.bs(t.data(),32);ok=encoded&&digest(out,ew.n,d)&&binding(k,d,a)&&continuity(k,c);wipe(body.data(),body.size());wipe(ai.data(),ai.size());wipe(t.data(),32);if(!ok){r.status=encoded?context_store_protected_registry_successor_status::invalid_policy:context_store_protected_registry_successor_status::output_too_small;wipe(d.data(),32);wipe(a.data(),32);wipe(c.data(),32);return r;}r.encoded_size=ew.n;r.set_authenticated(b,k,d,a,c,out,ew.n);wipe(d.data(),32);wipe(a.data(),32);wipe(c.data(),32);return r;}
context_store_protected_registry_successor_result context_store_verify_protected_registry_successor_v1(const uint8_t*p,size_t n,const context_store_protected_registry_key_record&k)noexcept{context_store_protected_registry_successor_result out;if(!p||!n||n>1024)return out;if(!keyok(k)){out.status=context_store_protected_registry_successor_status::invalid_policy;return out;}reader r{p,n};uint64_t z,alg,gen;const uint8_t*ip,*tp;size_t in,tn;if(!r.head(5,z)||z!=2||!r.ex(0))return out;size_t ao=r.o;if(!r.head(5,z)||z!=4||!r.ex(0))return out;context_store_protected_registry_successor_body b;if(!body_parse(r,b)||!r.ex(1)||!r.bytes(3,ip,in)||!r.ex(2)||!r.u(alg)||!r.ex(3)||!r.u(gen)||alg!=1)return out;size_t an=r.o-ao;if(!r.ex(1)||!r.bytes(2,tp,tn)||tn!=32||r.o!=n)return out;context_store_registered_id id;if(!in||in>128)return out;id.size=(uint8_t)in;std::copy_n(ip,in,id.bytes.begin());if(!idok(id))return out;if(!eqid(id,k.key_id)){out.status=context_store_protected_registry_successor_status::unknown_key;return out;}if(k.disposition==context_store_key_disposition::revoked){out.status=context_store_protected_registry_successor_status::revoked_key;return out;}if(k.disposition==context_store_key_disposition::read_disabled){out.status=context_store_protected_registry_successor_status::read_disabled_key;return out;}if(k.disposition!=context_store_key_disposition::active){out.status=context_store_protected_registry_successor_status::invalid_policy;return out;}if(gen!=k.generation){out.status=context_store_protected_registry_successor_status::key_generation_mismatch;return out;}context_store_format_digest e{},got{},d{},a{},c{};std::copy_n(tp,32,got.begin());if(!tag(k,p+ao,an,e)||!eqd(e,got)){out.status=context_store_protected_registry_successor_status::authentication_failed;wipe(e.data(),32);wipe(got.data(),32);return out;}if(!digest(p,n,d)||!binding(k,d,a)||!continuity(k,c)){out.status=context_store_protected_registry_successor_status::invalid_policy;wipe(e.data(),32);wipe(got.data(),32);wipe(d.data(),32);wipe(a.data(),32);wipe(c.data(),32);return out;}out.encoded_size=n;out.set_authenticated(b,k,d,a,c,p,n);wipe(e.data(),32);wipe(got.data(),32);wipe(d.data(),32);wipe(a.data(),32);wipe(c.data(),32);return out;}
const char*context_store_protected_registry_successor_status_name(context_store_protected_registry_successor_status s)noexcept{switch(s){case context_store_protected_registry_successor_status::authenticated_unadmitted:return "authenticated-unadmitted";case context_store_protected_registry_successor_status::structural_rejection:return "structural-rejection";case context_store_protected_registry_successor_status::output_too_small:return "output-too-small";case context_store_protected_registry_successor_status::invalid_policy:return "invalid-policy";case context_store_protected_registry_successor_status::unknown_key:return "unknown-key";case context_store_protected_registry_successor_status::revoked_key:return "revoked-key";case context_store_protected_registry_successor_status::read_disabled_key:return "read-disabled-key";case context_store_protected_registry_successor_status::key_generation_mismatch:return "key-generation-mismatch";case context_store_protected_registry_successor_status::authentication_failed:return "authentication-failed";}return "unknown";}
} // namespace halofpx
