if(NOT DEFINED BUILD_ROOT OR NOT DEFINED CONFIG)
  message(FATAL_ERROR "negative probe requires BUILD_ROOT and CONFIG")
endif()

function(run_probe TARGET EXPECT_SUCCESS EXPECT_PHASE)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" --build "${BUILD_ROOT}" --config "${CONFIG}" --target "${TARGET}"
    RESULT_VARIABLE RC OUTPUT_VARIABLE OUT ERROR_VARIABLE ERR)
  set(LOG "${OUT}\n${ERR}")
  if(EXPECT_SUCCESS)
    if(NOT RC EQUAL 0)
      message(FATAL_ERROR "positive detector control failed (${RC}):\n${LOG}")
    endif()
  else()
    if(RC EQUAL 0)
      message(FATAL_ERROR "${EXPECT_PHASE} negative probe unexpectedly built")
    endif()
    string(FIND "${LOG}" "concrete_registry_lab_observation" NAME_HIT)
    if(NAME_HIT EQUAL -1)
      message(FATAL_ERROR "${EXPECT_PHASE} negative probe failed for an unrelated reason:\n${LOG}")
    endif()
    if(EXPECT_PHASE STREQUAL "link")
      if(NOT LOG MATCHES "(unresolved external|LNK2019|undefined reference)")
        message(FATAL_ERROR "link-negative probe did not reach the linker:\n${LOG}")
      endif()
    else()
      if(LOG MATCHES "(unresolved external|LNK2019|undefined reference)")
        message(FATAL_ERROR "construction-negative probe unexpectedly reached link phase:\n${LOG}")
      endif()
    endif()
  endif()
endfunction()

run_probe(halofpx-registry-lab-positive-probe TRUE positive)
run_probe(halofpx-registry-lab-negative-construct FALSE compile)
run_probe(halofpx-registry-lab-negative-link FALSE link)
message(STATUS "PASS: concrete-observation compile/link negative probes and positive control")
