foreach(REQUIRED IN ITEMS BUILD_ROOT CONFIG ARCHIVE_MANIFEST
        READ_ONLY_ARCHIVE_MANIFEST NM_TOOL AR_TOOL READELF_TOOL)
  if(NOT DEFINED ${REQUIRED})
    message(FATAL_ERROR "Linux archive audit missing ${REQUIRED}")
  endif()
endforeach()
execute_process(
  COMMAND "${CMAKE_COMMAND}" --build "${BUILD_ROOT}" --config "${CONFIG}"
          --target halofpx-registry-lab-linux-audit-inputs
  RESULT_VARIABLE BUILD_RC OUTPUT_VARIABLE BUILD_OUT ERROR_VARIABLE BUILD_ERR)
if(NOT BUILD_RC EQUAL 0)
  message(FATAL_ERROR "failed to build Linux audit inputs:\n${BUILD_OUT}\n${BUILD_ERR}")
endif()
execute_process(
  COMMAND "${CMAKE_COMMAND}" --build "${BUILD_ROOT}" --config "${CONFIG}"
          --target halofpx-registry-lab-read-only-linux-audit-inputs
  RESULT_VARIABLE READ_ONLY_BUILD_RC OUTPUT_VARIABLE READ_ONLY_BUILD_OUT
  ERROR_VARIABLE READ_ONLY_BUILD_ERR)
if(NOT READ_ONLY_BUILD_RC EQUAL 0)
  message(FATAL_ERROR "failed to build Linux read-only audit inputs:\n${READ_ONLY_BUILD_OUT}\n${READ_ONLY_BUILD_ERR}")
endif()
include("${ARCHIVE_MANIFEST}")
list(LENGTH HALOFPX_REGISTRY_LAB_ARCHIVES ARCHIVE_COUNT)
if(NOT ARCHIVE_COUNT EQUAL 6)
  message(FATAL_ERROR "Linux audit requires exactly six closure archives")
endif()
include("${READ_ONLY_ARCHIVE_MANIFEST}")
list(LENGTH HALOFPX_REGISTRY_LAB_READ_ONLY_ARCHIVES READ_ONLY_ARCHIVE_COUNT)
if(NOT READ_ONLY_ARCHIVE_COUNT EQUAL 7)
  message(FATAL_ERROR "Linux read-only audit requires exactly seven closure archives")
endif()
set(ALL_REGISTRY_LAB_ARCHIVES
  ${HALOFPX_REGISTRY_LAB_ARCHIVES}
  ${HALOFPX_REGISTRY_LAB_READ_ONLY_ARCHIVES})
list(REMOVE_DUPLICATES ALL_REGISTRY_LAB_ARCHIVES)
list(LENGTH ALL_REGISTRY_LAB_ARCHIVES ALL_ARCHIVE_COUNT)
if(NOT ALL_ARCHIVE_COUNT EQUAL 7)
  message(FATAL_ERROR "Linux wire/read-only archive union must contain exactly seven archives")
endif()
set(FORBIDDEN_SYMBOLS
  concrete_registry_lab_observation bootstrap_material bootstrap_anchor
  context_store_publication context_store_cache context_store_restore
  llama-ai CachyLLama)
function(assert_clean_symbols TEXT LABEL)
  string(TOLOWER "${TEXT}" TEXT_LOWER)
  foreach(FORBIDDEN IN LISTS FORBIDDEN_SYMBOLS)
    string(TOLOWER "${FORBIDDEN}" FORBIDDEN_LOWER)
    string(FIND "${TEXT_LOWER}" "${FORBIDDEN_LOWER}" HIT)
    if(NOT HIT EQUAL -1)
      message(FATAL_ERROR "forbidden Linux symbol ${FORBIDDEN} in ${LABEL}")
    endif()
  endforeach()
  string(REPLACE "\r\n" "\n" NORMALIZED_TEXT "${TEXT}")
  string(REPLACE "\n" ";" SYMBOL_LINES "${NORMALIZED_TEXT}")
  foreach(SYMBOL_LINE IN LISTS SYMBOL_LINES)
    if(SYMBOL_LINE MATCHES "(^|[ \t])(U|UND)([ \t])" AND
       SYMBOL_LINE MATCHES "(^|[^A-Za-z0-9_])(openat|fsync|fdatasync|rename|unlink|getenv|system)(@[^ \t]*)?($|[^A-Za-z0-9_])")
      message(FATAL_ERROR "forbidden Linux undefined OS symbol in ${LABEL}: ${SYMBOL_LINE}")
    endif()
  endforeach()
endfunction()

function(find_allocator_import TEXT OUT_VAR)
  string(REPLACE "\r\n" "\n" NORMALIZED_TEXT "${TEXT}")
  string(REPLACE "\n" ";" SYMBOL_LINES "${NORMALIZED_TEXT}")
  set(FOUND "")
  foreach(SYMBOL_LINE IN LISTS SYMBOL_LINES)
    string(TOLOWER "${SYMBOL_LINE}" SYMBOL_LINE_LOWER)
    if(SYMBOL_LINE_LOWER MATCHES "(^|[ \\t])(u|und)([ \\t])" AND
       SYMBOL_LINE_LOWER MATCHES "(^|[^a-z0-9_])(malloc|calloc|realloc|operator new)([^a-z0-9_]|$)")
      set(FOUND "${SYMBOL_LINE}")
      break()
    endif()
  endforeach()
  set(${OUT_VAR} "${FOUND}" PARENT_SCOPE)
endfunction()
find_allocator_import("archive.o: U operator new(unsigned long)" SYNTHETIC_ALLOCATOR)
if(SYNTHETIC_ALLOCATOR STREQUAL "")
  message(FATAL_ERROR "Linux allocator-import detector synthetic positive self-test failed")
endif()
find_allocator_import("archive.o: U memcpy" SYNTHETIC_NON_ALLOCATOR)
if(NOT SYNTHETIC_NON_ALLOCATOR STREQUAL "")
  message(FATAL_ERROR "Linux allocator-import detector benign self-test failed")
endif()

set(OBJECT_ROOT "${BUILD_ROOT}/halofpx-registry-lab-linux-object-audit/${CONFIG}")
file(MAKE_DIRECTORY "${OBJECT_ROOT}")
set(ARCHIVE_INDEX 0)
foreach(ARCHIVE IN LISTS ALL_REGISTRY_LAB_ARCHIVES)
  if(NOT EXISTS "${ARCHIVE}")
    message(FATAL_ERROR "missing Linux closure archive: ${ARCHIVE}")
  endif()
  execute_process(COMMAND "${AR_TOOL}" t "${ARCHIVE}"
    RESULT_VARIABLE AR_RC OUTPUT_VARIABLE MEMBERS ERROR_VARIABLE AR_ERR)
  if(NOT AR_RC EQUAL 0)
    message(FATAL_ERROR "ar inventory failed for ${ARCHIVE}: ${AR_ERR}")
  endif()
  string(REGEX REPLACE "[\r\n]+" ";" MEMBER_LIST "${MEMBERS}")
  list(FILTER MEMBER_LIST EXCLUDE REGEX "^$")
  if(NOT MEMBER_LIST)
    message(FATAL_ERROR "empty Linux closure archive: ${ARCHIVE}")
  endif()
  execute_process(COMMAND "${NM_TOOL}" -A -u -C "${ARCHIVE}"
    RESULT_VARIABLE NM_RC OUTPUT_VARIABLE NM_UNDEFINED ERROR_VARIABLE NM_ERR)
  if(NOT NM_RC EQUAL 0)
    message(FATAL_ERROR "nm undefined-symbol audit failed for ${ARCHIVE}: ${NM_ERR}")
  endif()
  assert_clean_symbols("${NM_UNDEFINED}" "${ARCHIVE} undefined symbols")
  if(ARCHIVE MATCHES "halofpx-context-store-registry-lab-read-only")
    find_allocator_import("${NM_UNDEFINED}" ARCHIVE_ALLOCATOR)
    if(NOT ARCHIVE_ALLOCATOR STREQUAL "")
      message(FATAL_ERROR "allocator import in allocation-free Linux read-only archive ${ARCHIVE}: ${ARCHIVE_ALLOCATOR}")
    endif()
  endif()
  execute_process(COMMAND "${NM_TOOL}" -A --defined-only -C "${ARCHIVE}"
    RESULT_VARIABLE NM_DEFINED_RC OUTPUT_VARIABLE NM_DEFINED ERROR_VARIABLE NM_DEFINED_ERR)
  if(NOT NM_DEFINED_RC EQUAL 0)
    message(FATAL_ERROR "nm defined-symbol audit failed for ${ARCHIVE}: ${NM_DEFINED_ERR}")
  endif()
  assert_clean_symbols("${NM_DEFINED}" "${ARCHIVE} defined symbols")
  set(MEMBER_INDEX 0)
  foreach(MEMBER IN LISTS MEMBER_LIST)
    set(OBJECT_FILE "${OBJECT_ROOT}/archive-${ARCHIVE_INDEX}-member-${MEMBER_INDEX}.o")
    execute_process(COMMAND "${AR_TOOL}" p "${ARCHIVE}" "${MEMBER}"
      RESULT_VARIABLE EXTRACT_RC OUTPUT_FILE "${OBJECT_FILE}" ERROR_VARIABLE EXTRACT_ERR)
    if(NOT EXTRACT_RC EQUAL 0)
      message(FATAL_ERROR "ar member extraction failed for ${ARCHIVE}(${MEMBER}): ${EXTRACT_ERR}")
    endif()
    execute_process(COMMAND "${READELF_TOOL}" -Ws "${OBJECT_FILE}"
      RESULT_VARIABLE ELF_RC OUTPUT_VARIABLE ELF_SYMBOLS ERROR_VARIABLE ELF_ERR)
    if(NOT ELF_RC EQUAL 0 OR NOT ELF_SYMBOLS MATCHES "Symbol table")
      message(FATAL_ERROR "readelf symbol audit failed for ${ARCHIVE}(${MEMBER}): ${ELF_ERR}")
    endif()
    assert_clean_symbols("${ELF_SYMBOLS}" "${ARCHIVE}(${MEMBER}) ELF symbols")
    execute_process(COMMAND "${READELF_TOOL}" -d "${OBJECT_FILE}"
      RESULT_VARIABLE DYNAMIC_RC OUTPUT_VARIABLE DYNAMIC_TEXT ERROR_VARIABLE DYNAMIC_ERR)
    if(NOT DYNAMIC_RC EQUAL 0)
      message(FATAL_ERROR "readelf dynamic audit failed for ${ARCHIVE}(${MEMBER}): ${DYNAMIC_ERR}")
    endif()
    if(DYNAMIC_TEXT MATCHES "\\(NEEDED\\)|\\(SONAME\\)")
      message(FATAL_ERROR "relocatable audit object contains a dynamic import/SONAME: ${ARCHIVE}(${MEMBER})")
    endif()
    math(EXPR MEMBER_INDEX "${MEMBER_INDEX} + 1")
  endforeach()
  math(EXPR ARCHIVE_INDEX "${ARCHIVE_INDEX} + 1")
endforeach()
message(STATUS "PASS: Linux ar/nm/readelf archive and member-object audit")
