file(READ "${SOURCE_ROOT}/tools/server/CMakeLists.txt" SERVER_CMAKE)
file(READ "${SOURCE_ROOT}/tools/server/halofpx-context-store-protected-registry.cpp" SOURCE)
file(READ "${SOURCE_ROOT}/tools/server/halofpx-context-store-protected-registry.h" HEADER)
if(NOT SERVER_CMAKE MATCHES "halofpx-context-store-protected-registry STATIC EXCLUDE_FROM_ALL")
  message(FATAL_ERROR "protected registry must remain excluded")
endif()
if(SERVER_CMAKE MATCHES "server-context[^\n]*halofpx-context-store-protected-registry")
  message(FATAL_ERROR "protected registry entered runtime")
endif()
set(ALL "${SOURCE}\n${HEADER}")
foreach(FORBIDDEN "filesystem" "fstream" "fopen[ \\t]*\\(" "CreateFile" "rename[at0-9_]*[ \\t]*\\(" "protected_registry_id =" "last_consumed_sequence = 0;[\r\n]+[ \\t]*};[\r\n]+[\r\n]+struct context_store_bootstrap_authority_config")
  if(ALL MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "forbidden registry marker: ${FORBIDDEN}")
  endif()
endforeach()
foreach(REQUIRED "context_store_protected_registry_max_bytes = 1024" "authenticated_unadmitted" "halofpx.registry-snapshot-key.v1" "halofpx.registry-snapshot-auth.v1" "halofpx.registry-snapshot.v1" "w.head\\(5,4\\)" "e.head\\(5,2\\)" "tag\\(k,ai.data\\(\\),w.size,t\\)" "tstr" "wipe\\(")
  if(NOT ALL MATCHES "${REQUIRED}")
    message(FATAL_ERROR "missing registry marker: ${REQUIRED}")
  endif()
endforeach()
