if(NOT DEFINED ARCHIVE_MANIFEST OR NOT DEFINED NM_TOOL OR NOT DEFINED AR_TOOL)
  message(FATAL_ERROR "ARCHIVE_MANIFEST, NM_TOOL, and AR_TOOL are required")
endif()
include("${ARCHIVE_MANIFEST}")
if(NOT EXISTS "${HALOFPX_L05T_ARCHIVE}")
  message(FATAL_ERROR "L05t archive does not exist: ${HALOFPX_L05T_ARCHIVE}")
endif()

execute_process(COMMAND "${AR_TOOL}" t "${HALOFPX_L05T_ARCHIVE}"
  RESULT_VARIABLE AR_RESULT OUTPUT_VARIABLE MEMBERS ERROR_VARIABLE AR_ERROR)
if(NOT AR_RESULT EQUAL 0)
  message(FATAL_ERROR "archive listing failed: ${AR_ERROR}")
endif()
string(REGEX MATCHALL "[^\r\n]+" MEMBER_LINES "${MEMBERS}")
list(LENGTH MEMBER_LINES MEMBER_COUNT)
if(NOT MEMBER_COUNT EQUAL 1)
  message(FATAL_ERROR "L05t archive must contain exactly one seam object; got ${MEMBER_COUNT}")
endif()

execute_process(COMMAND "${NM_TOOL}" -g --defined-only --format=posix -C "${HALOFPX_L05T_ARCHIVE}"
  RESULT_VARIABLE DEFINED_RESULT OUTPUT_VARIABLE DEFINED ERROR_VARIABLE DEFINED_ERROR)
if(NOT DEFINED_RESULT EQUAL 0)
  message(FATAL_ERROR "defined-symbol audit failed: ${DEFINED_ERROR}")
endif()
string(REGEX MATCHALL "[^\r\n]+" DEFINED_LINES "${DEFINED}")
set(DEFINED_SYMBOL_LINES "")
foreach(LINE IN LISTS DEFINED_LINES)
  if(LINE MATCHES " [A-Za-z?] [0-9A-Fa-f]+ [0-9A-Fa-f]+$")
    list(APPEND DEFINED_SYMBOL_LINES "${LINE}")
  endif()
endforeach()
list(LENGTH DEFINED_SYMBOL_LINES DEFINED_SYMBOL_COUNT)
if(NOT DEFINED_SYMBOL_COUNT EQUAL 1)
  message(FATAL_ERROR "L05t archive must define exactly one global symbol: ${DEFINED}")
endif()
list(GET DEFINED_SYMBOL_LINES 0 DEFINED_SEAM)
string(FIND "${DEFINED_SEAM}"
  "halofpx::context_store_registry_lab_linux_initializer_predecessor_digest_v1" SEAM_SYMBOL)
if(SEAM_SYMBOL EQUAL -1)
  message(FATAL_ERROR "L05t archive's sole global definition is not the admitted seam: ${DEFINED}")
endif()
foreach(FORBIDDEN IN ITEMS " T open" " T read" " T write" " T rename" " T fsync"
    "server_context" "llama_server" "publication_coordinator")
  string(FIND "${DEFINED}" "${FORBIDDEN}" HIT)
  if(NOT HIT EQUAL -1)
    message(FATAL_ERROR "forbidden L05t defined symbol: ${FORBIDDEN}")
  endif()
endforeach()

execute_process(COMMAND "${NM_TOOL}" -u -C "${HALOFPX_L05T_ARCHIVE}"
  RESULT_VARIABLE UNDEFINED_RESULT OUTPUT_VARIABLE UNDEFINED ERROR_VARIABLE UNDEFINED_ERROR)
if(NOT UNDEFINED_RESULT EQUAL 0)
  message(FATAL_ERROR "undefined-symbol audit failed: ${UNDEFINED_ERROR}")
endif()
string(REGEX MATCHALL "[^\r\n]+" UNDEFINED_LINES "${UNDEFINED}")
set(UNDEFINED_SYMBOL_LINES "")
foreach(LINE IN LISTS UNDEFINED_LINES)
  if(LINE MATCHES "[ \t]U[ \t]")
    list(APPEND UNDEFINED_SYMBOL_LINES "${LINE}")
  endif()
endforeach()
set(HALOFPX_IMPORT_COUNT 0)
foreach(LINE IN LISTS UNDEFINED_SYMBOL_LINES)
  if(LINE MATCHES "halofpx::")
    math(EXPR HALOFPX_IMPORT_COUNT "${HALOFPX_IMPORT_COUNT} + 1")
    string(FIND "${LINE}"
      "halofpx::context_store_registry_lab_registry_envelope_digest_v1" DIGEST_IMPORT)
    if(DIGEST_IMPORT EQUAL -1)
      message(FATAL_ERROR "L05t archive imports an unadmitted HaloFPX symbol: ${LINE}")
    endif()
  elseif(SANITIZED_BUILD AND LINE MATCHES "[ \t]U[ \t]+__(asan|ubsan)_")
    # Compiler sanitizer runtime only; it carries no project or I/O authority.
  else()
    message(FATAL_ERROR "L05t archive imports an unadmitted symbol: ${LINE}")
  endif()
endforeach()
if(NOT HALOFPX_IMPORT_COUNT EQUAL 1)
  message(FATAL_ERROR "L05t archive must import exactly one HaloFPX digest symbol: ${UNDEFINED}")
endif()
if(NOT SANITIZED_BUILD)
  list(LENGTH UNDEFINED_SYMBOL_LINES UNDEFINED_COUNT)
  if(NOT UNDEFINED_COUNT EQUAL 1)
    message(FATAL_ERROR "unsanitized L05t archive must import exactly one symbol: ${UNDEFINED}")
  endif()
endif()
foreach(FORBIDDEN IN ITEMS " open" " read" " write" " rename" " fsync" "fdatasync"
    "mkdir" "unlink" "system" "fork" "exec")
  string(FIND "${UNDEFINED}" "${FORBIDDEN}" HIT)
  if(NOT HIT EQUAL -1)
    message(FATAL_ERROR "forbidden L05t imported symbol: ${FORBIDDEN}")
  endif()
endforeach()

message(STATUS "PASS: L05t initializer archive/import isolation")
