set(ROOT "${SOURCE_ROOT}")
set(H "${ROOT}/tools/server/halofpx-context-store-registry-lab-wire.h")
set(C "${ROOT}/tools/server/halofpx-context-store-registry-lab-wire.cpp")
foreach(F IN ITEMS "${H}" "${C}")
  if(NOT EXISTS "${F}")
    message(FATAL_ERROR "missing L05o wire source: ${F}")
  endif()
  file(READ "${F}" TEXT)
  foreach(FORBIDDEN IN ITEMS
      "open(" "fopen(" "freopen(" "read(" "write(" "rename(" "remove("
      "fsync(" "fdatasync(" "mkdir(" "unlink(" "CreateFile" "ReadFile"
      "WriteFile" "MoveFile" "DeleteFile" "std::filesystem" "#include <filesystem>"
      "#include <fstream>" "std::ifstream" "std::ofstream" "getenv(" "system("
      "halofpx-context-store-bootstrap-consumption"
      "halofpx-context-store-bootstrap-material"
      "halofpx-context-store-bootstrap-anchor")
    string(FIND "${TEXT}" "${FORBIDDEN}" HIT)
    if(NOT HIT EQUAL -1)
      message(FATAL_ERROR "L05o wire slice contains forbidden I/O/syscall token ${FORBIDDEN}: ${F}")
    endif()
  endforeach()
endforeach()
file(READ "${ROOT}/tools/server/CMakeLists.txt" SERVER_CMAKE)
if(NOT SERVER_CMAKE MATCHES "add_library\\(halofpx-context-store-registry-lab-wire STATIC EXCLUDE_FROM_ALL")
  message(FATAL_ERROR "L05o wire target is not explicitly EXCLUDE_FROM_ALL")
endif()
string(FIND "${SERVER_CMAKE}" "target_link_libraries(halofpx-context-store-registry-lab-wire PUBLIC\n    halofpx-context-store-registry-successor)" NARROW_LINK)
if(NARROW_LINK EQUAL -1)
  message(FATAL_ERROR "L05o wire target does not use the narrow registry-successor dependency")
endif()
string(FIND "${SERVER_CMAKE}" "set(TARGET server-context)" PRODUCT_MARKER)
if(PRODUCT_MARKER EQUAL -1)
  message(FATAL_ERROR "server product marker is missing")
endif()
string(SUBSTRING "${SERVER_CMAKE}" ${PRODUCT_MARKER} -1 PRODUCT_TAIL)
string(FIND "${PRODUCT_TAIL}" "server-context.cpp" PRODUCT_SENTINEL)
if(PRODUCT_SENTINEL EQUAL -1)
  message(FATAL_ERROR "product-tail extraction did not cross line boundaries")
endif()
string(FIND "${PRODUCT_TAIL}" "halofpx-context-store-registry-lab-wire" PRODUCT_LEAK)
if(NOT PRODUCT_LEAK EQUAL -1)
  message(FATAL_ERROR "L05o wire target leaked into product/server linkage")
endif()
set(SYNTHETIC_LEAK "${PRODUCT_TAIL}\nhalofpx-context-store-registry-lab-wire")
string(FIND "${SYNTHETIC_LEAK}" "halofpx-context-store-registry-lab-wire" SYNTHETIC_HIT)
if(SYNTHETIC_HIT EQUAL -1)
  message(FATAL_ERROR "product-link leakage detector failed its synthetic self-test")
endif()
message(STATUS "PASS: L05o wire/static feature-off contract")
