#include "halofpx-context-store-protected-registry-successor.h"

#include <algorithm>
#include <array>
#include <cassert>
#include <cstdint>
#include <string>
#include <type_traits>
#include <vector>

using namespace halofpx;
namespace {
context_store_registered_id id(const char*s){context_store_registered_id v;while(s[v.size]){v.bytes[v.size]=s[v.size];++v.size;}return v;}
std::array<uint8_t,32> hex(const char*s){std::array<uint8_t,32>v{};auto h=[](char c){return uint8_t(c<='9'?c-'0':c-'a'+10);};for(size_t i=0;i<32;++i)v[i]=uint8_t(h(s[2*i])<<4|h(s[2*i+1]));return v;}
struct fixture{std::array<uint8_t,32>secret{};context_store_protected_registry_key_record key;fixture(){secret.fill(0x44);key={context_store_key_disposition::active,id("registry-auth-v1"),13,{secret.data(),secret.size()}};}};
context_store_protected_registry_successor_body body(){context_store_protected_registry_successor_body b;b.registry_id=id("registry-v1");b.registry_epoch=9;b.authority_base_scope_commitment.fill(0xaa);b.policy_commitment.fill(0xbb);b.consumed_authorization_high_water=41;b.predecessor_snapshot_envelope_digest=hex("a7b731bccfdea83a4595d5257ffa34ef9248bb61499b40a37874895cff6bc1ec");b.receipt.authorization_sequence=41;b.receipt.command_id.fill(0xcc);b.receipt.authorization_token_digest.fill(0xdd);b.receipt.plan_commitment.fill(0xee);b.receipt.selected_manifest_digest.fill(0x11);b.receipt.proposed_anchor_envelope_digest.fill(0x22);return b;}
void positive_and_golden(){fixture f;std::array<uint8_t,1024>bytes{};auto e=context_store_encode_protected_registry_successor_v1(body(),f.key,bytes.data(),bytes.size());assert(e.status==context_store_protected_registry_successor_status::authenticated_unadmitted&&e.encoded_size==371);auto*c=e.authenticated_carrier();assert(c&&c->envelope_size()==371&&std::equal(bytes.begin(),bytes.begin()+371,c->envelope_data()));assert(*c->envelope_digest()==hex("fd1a86a341a6b90639e7fa31730d1c77fcbc898ce11b527d241b9d55325069e2"));assert(*c->key_continuity_commitment()==hex("3390a19271852403712dac091321cebfac9abb640422d81ae4136cc7a7cc7386"));assert(std::equal(bytes.begin()+339,bytes.begin()+371,hex("1f3f79689d0b2dd37988aac8c92bf90be6689b0079bd5fc4a7066973fdebd202").begin()));auto v=context_store_verify_protected_registry_successor_v1(bytes.data(),371,f.key);assert(v.authenticated_carrier()&&*v.authenticated_carrier()->envelope_digest()==*c->envelope_digest());for(size_t n=0;n<371;++n)assert(!context_store_verify_protected_registry_successor_v1(bytes.data(),n,f.key).authenticated_carrier());for(size_t i=0;i<371;++i){auto x=bytes;x[i]^=1;assert(!context_store_verify_protected_registry_successor_v1(x.data(),371,f.key).authenticated_carrier());}}
void malformed_and_policy(){fixture f;std::array<uint8_t,1024>bytes{};auto good=context_store_encode_protected_registry_successor_v1(body(),f.key,bytes.data(),bytes.size());auto x=bytes;x[0]=0xa3;assert(context_store_verify_protected_registry_successor_v1(x.data(),good.encoded_size,f.key).status==context_store_protected_registry_successor_status::structural_rejection);std::vector<uint8_t>nc(good.encoded_size+1);nc[0]=0xb8;nc[1]=2;std::copy_n(bytes.begin()+1,good.encoded_size-1,nc.begin()+2);assert(context_store_verify_protected_registry_successor_v1(nc.data(),nc.size(),f.key).status==context_store_protected_registry_successor_status::structural_rejection);auto b=body();b.receipt.command_id.fill(0);assert(context_store_encode_protected_registry_successor_v1(b,f.key,bytes.data(),bytes.size()).status==context_store_protected_registry_successor_status::invalid_policy);b=body();++b.receipt.authorization_sequence;assert(context_store_encode_protected_registry_successor_v1(b,f.key,bytes.data(),bytes.size()).status==context_store_protected_registry_successor_status::invalid_policy);b=body();b.predecessor_snapshot_envelope_digest.fill(0);assert(context_store_encode_protected_registry_successor_v1(b,f.key,bytes.data(),bytes.size()).status==context_store_protected_registry_successor_status::invalid_policy);auto other=f.key;other.key_id=id("other");assert(context_store_verify_protected_registry_successor_v1(bytes.data(),good.encoded_size,other).status==context_store_protected_registry_successor_status::unknown_key);assert(context_store_encode_protected_registry_successor_v1(body(),f.key,bytes.data(),1).status==context_store_protected_registry_successor_status::output_too_small);}
void predecessor_continuity(){fixture f;context_store_protected_registry_body b;b.registry_id=id("registry-v1");b.registry_epoch=9;b.authority_base_scope_commitment.fill(0xaa);b.policy_commitment.fill(0xbb);b.last_consumed_sequence=40;std::array<uint8_t,1024>p{},s{};auto pe=context_store_encode_protected_registry_v1(b,f.key,p.data(),p.size());auto se=context_store_encode_protected_registry_successor_v1(body(),f.key,s.data(),s.size());assert(*pe.authenticated_carrier()->key_continuity_commitment()==*se.authenticated_carrier()->key_continuity_commitment());assert(pe.authenticated_carrier()->envelope_size()==156);auto other=f;other.secret[0]^=1;other.key.master_key={other.secret.data(),other.secret.size()};auto oe=context_store_encode_protected_registry_successor_v1(body(),other.key,s.data(),s.size());assert(*oe.authenticated_carrier()->key_continuity_commitment()!=*pe.authenticated_carrier()->key_continuity_commitment());}
}
int main(){static_assert(context_store_protected_registry_successor_max_bytes==1024);static_assert(!std::is_aggregate_v<context_store_authenticated_protected_registry_successor>);positive_and_golden();malformed_and_policy();predecessor_continuity();}
