if(NOT DEFINED SOURCE_ROOT)
  message(FATAL_ERROR "SOURCE_ROOT required")
endif()
set(H "${SOURCE_ROOT}/tools/server/halofpx-context-store-bootstrap-consumption.h")
set(S "${SOURCE_ROOT}/tools/server/halofpx-context-store-bootstrap-consumption.cpp")
file(READ "${H}" HT)
file(READ "${S}" ST)
file(READ "${SOURCE_ROOT}/tools/server/CMakeLists.txt" CT)
foreach(REQUIRED "EXCLUDE_FROM_ALL" "halofpx-context-store-bootstrap-consumption" "halofpx.bootstrap-consumption-operation.v1" "advanced_unexecuted" "already_consumed_same_unexecuted" "late_completion_risk" "key_continuity_commitment" "operation_commitment" "observed_current" "exact_successor" "std::atomic<bool>" "friend class context_store_bootstrap_consumption_coordinator" "predecessor()" "root_identity()" "attempt_id()" "command_id()" "authorization_token_digest()" "plan_commitment()" "authority_snapshot_commitment()" "selected_manifest_digest()" "classified_outcome()" "quarantined_" "terminal_attempts_" "wipe\\(")
  if(NOT "${CT}${HT}${ST}" MATCHES "${REQUIRED}")
    message(FATAL_ERROR "missing L05k contract marker: ${REQUIRED}")
  endif()
endforeach()
if(NOT HT MATCHES "private:[\r\n \t]+context_store_bootstrap_backend_outcome execute[ \t]*\\(")
  message(FATAL_ERROR "backend execute must remain private and coordinator-only")
endif()
foreach(FORBIDDEN "filesystem" "fstream" "fopen[ \\t]*\\(" "CreateFile" "rename[at0-9_]*[ \\t]*\\(" "server-context" "std::thread" "sleep_for" "socket" "curl")
  if("${HT}${ST}" MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "forbidden L05k production surface: ${FORBIDDEN}")
  endif()
endforeach()
if(CT MATCHES "target_link_libraries\\(server-context[^)]*bootstrap-consumption")
  message(FATAL_ERROR "L05k linked into server-context")
endif()
