file(READ "${SOURCE_ROOT}/tools/server/CMakeLists.txt" SERVER_CMAKE)
file(READ "${SOURCE_ROOT}/tools/server/halofpx-context-store-bootstrap-token.cpp" TOKEN_SOURCE)
file(READ "${SOURCE_ROOT}/tools/server/halofpx-context-store-bootstrap-token.h" TOKEN_HEADER)
set(TOKEN_ALL "${TOKEN_SOURCE}\n${TOKEN_HEADER}")
if(NOT SERVER_CMAKE MATCHES "halofpx-context-store-bootstrap-token STATIC EXCLUDE_FROM_ALL")
    message(FATAL_ERROR "bootstrap token codec must remain EXCLUDE_FROM_ALL")
endif()
if(SERVER_CMAKE MATCHES "server-context[^\n]*halofpx-context-store-bootstrap-token")
    message(FATAL_ERROR "bootstrap token codec entered server runtime")
endif()
foreach(FORBIDDEN "filesystem" "fstream" "fopen[ \t]*\\(" "CreateFile" "openat" "rename[at0-9_]*[ \t]*\\(" "context_store_provider" "server-context" "w.head\\(5,5\\)")
    if(TOKEN_ALL MATCHES "${FORBIDDEN}")
        message(FATAL_ERROR "forbidden runtime or I/O marker: ${FORBIDDEN}")
    endif()
endforeach()
foreach(REQUIRED "context_store_bootstrap_token_max_bytes = 2048" "authenticated_unconsumed" "output_too_small" "halofpx.bootstrap-token-key.v1" "halofpx.bootstrap-token-auth.v1" "halofpx.bootstrap-token.v1" "operation_bootstrap" "algorithm_hmac_sha256" "authority_scope_commitment" "protected_registry_snapshot_digest" "authorization_sequence" "command_id" "auth.head\\(5,4\\)" "w.head\\(5,2\\)" "make_tag\\(key,auth_input.data\\(\\),auth.size,tag\\)" "wipe\\(")
    if(NOT TOKEN_ALL MATCHES "${REQUIRED}")
        message(FATAL_ERROR "missing bootstrap-token contract marker: ${REQUIRED}")
    endif()
endforeach()
