#ifdef NDEBUG
#undef NDEBUG
#endif
#include "halofpx-context-store-registry-lab-wire.h"

#include <algorithm>
#include <array>
#include <cassert>
#include <cstdint>
#include <fstream>
#include <iterator>
#include <new>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

using namespace halofpx;
static_assert(!std::is_same_v<context_store_registry_lab_root_witness, context_store_registry_lab_head_witness>);
static_assert(!std::is_same_v<context_store_registry_lab_head_witness, context_store_registry_lab_prepare_witness>);
static_assert(!std::is_same_v<context_store_registry_lab_prepare_witness, context_store_registry_lab_close_witness>);
static_assert(!std::is_same_v<context_store_registry_lab_close_witness, context_store_registry_lab_abort_witness>);
static_assert(!std::is_same_v<context_store_registry_lab_abort_witness, context_store_registry_lab_quarantine_witness>);
static_assert(offsetof(context_store_registry_lab_quarantine_evidence_v1,standalone_predecessor_head_value)>
    offsetof(context_store_registry_lab_quarantine_evidence_v1,prepare_size));
using root_encoder_v1 = context_store_registry_lab_wire_result (*)(const context_store_registry_lab_root_value_v1 &,
    const context_store_registry_lab_credential &, const context_store_registry_lab_root_witness &,
    uint8_t *, size_t, size_t &) noexcept;
constexpr root_encoder_v1 typed_root_encoder_v1 = &context_store_registry_lab_encode_root_v1;
static_assert(!std::is_invocable_v<root_encoder_v1, const context_store_registry_lab_root_value_v1 &,
    const context_store_registry_lab_credential &, const context_store_registry_lab_head_witness &,
    uint8_t *, size_t, size_t &>);
using close_encoder_v1 = context_store_registry_lab_wire_result (*)(const context_store_registry_lab_close_value_v1 &,
    const context_store_registry_lab_credential &, const context_store_registry_lab_close_witness &,
    uint8_t *, size_t, size_t &) noexcept;
constexpr close_encoder_v1 typed_close_encoder_v1 = &context_store_registry_lab_encode_close_v1;
static_assert(!std::is_invocable_v<close_encoder_v1, const context_store_registry_lab_abort_value_v1 &,
    const context_store_registry_lab_credential &, const context_store_registry_lab_abort_witness &,
    uint8_t *, size_t, size_t &>);
namespace {
uint8_t nibble(char c){return uint8_t(c<='9'?c-'0':c-'a'+10);}
std::vector<uint8_t> hex_bytes(const std::string&s){assert(s.size()%2==0);std::vector<uint8_t>v(s.size()/2);for(size_t i=0;i<v.size();++i)v[i]=uint8_t(nibble(s[2*i])<<4|nibble(s[2*i+1]));return v;}
context_store_format_digest digest(const char*s){auto v=hex_bytes(s);assert(v.size()==32);context_store_format_digest d{};std::copy(v.begin(),v.end(),d.begin());return d;}
context_store_registered_id id(const char*s){context_store_registered_id x;while(s[x.size]){x.bytes[x.size]=s[x.size];++x.size;}return x;}
std::string value(const std::string&json,const std::string&key,size_t from=0){auto p=json.find("\""+key+"\"",from);assert(p!=std::string::npos);p=json.find(':',p)+1;p=json.find('"',p)+1;auto e=json.find('"',p);return json.substr(p,e-p);}
std::vector<uint8_t> fixture(const std::string&json,const char*name){auto p=json.find("\""+std::string(name)+"\"");assert(p!=std::string::npos);return hex_bytes(value(json,"envelope_hex",p));}
struct setup {
 std::array<uint8_t,32> secret{}; context_store_registry_lab_credential credential; context_store_registry_lab_expectation expect; std::array<uint8_t,1024> pred{},succ{};
 setup(uint64_t high=40,uint64_t delta=1){secret.fill(0x44);credential.key_id=id("registry-auth-v1");credential.generation=13;credential.secret=secret;context_store_protected_registry_key_record k{context_store_key_disposition::active,credential.key_id,13,{secret.data(),secret.size()}};context_store_protected_registry_body pb;pb.registry_id=id("registry-v1");pb.registry_epoch=9;pb.authority_base_scope_commitment.fill(0xaa);pb.policy_commitment.fill(0xbb);pb.last_consumed_sequence=high;auto pe=context_store_encode_protected_registry_v1(pb,k,pred.data(),pred.size());assert(pe.authenticated_carrier());context_store_protected_registry_successor_body sb;sb.registry_id=pb.registry_id;sb.registry_epoch=9;sb.authority_base_scope_commitment=pb.authority_base_scope_commitment;sb.policy_commitment=pb.policy_commitment;sb.consumed_authorization_high_water=high+delta;sb.predecessor_snapshot_envelope_digest=*pe.authenticated_carrier()->envelope_digest();sb.receipt.authorization_sequence=high+delta;sb.receipt.command_id.fill(0xcc);sb.receipt.authorization_token_digest.fill(0xdd);sb.receipt.plan_commitment.fill(0xee);sb.receipt.selected_manifest_digest.fill(0x11);sb.receipt.proposed_anchor_envelope_digest.fill(0x22);auto se=context_store_encode_protected_registry_successor_v1(sb,k,succ.data(),succ.size());assert(se.authenticated_carrier());expect.root_id.fill(0x11);expect.store_uuid.fill(0x22);expect.filesystem_uuid.fill(0x44);expect.registry_id=pb.registry_id;expect.registry_epoch=9;expect.predecessor_high_water=high;expect.predecessor_selector_generation=1;expect.successor_selector_generation=2;expect.mount_id=731;expect.owner_uid=1000;expect.lock_st_dev=2049;expect.lock_st_ino=987654;expect.path_policy_commitment=digest("162c7c9272841ccdec5dbf024d1d8dd511dbb4e2f538d8cdbab830e06abc9c0d");expect.initial_head_digest=digest("93ea1f031d4ec2827bc28535d56f2a0a1f6efb49ecff9ed763cf03bced0c0d82");expect.successor_head_digest=digest("d3d372ef42c5254a2baca52ba35cae46899cdf0e464396e3fa272ffc238a309b");expect.predecessor_envelope_digest=digest("5b6ea5887d96bf20c176e2346c2478149a8b7bcf1d84dc98843c28f4e00d0b9e");expect.successor_envelope_digest=digest("ee621ab3efa4c76cc2e2132034a404d6a373701ad8772f0576fd5bd20087c5cd");expect.prepare_digest=digest("9ea5eced3354b6a90ca306361568de879d5ebfc9effd63de6f73629c04baa8fa");expect.operation_commitment=digest("f28cb18e21d74d63346bddacbd482e28a55989cfa2f9e18cea382792a89b7fb1");expect.attempt_id.fill(0x66);expect.quarantine_event_id.fill(0x77);expect.quarantine_attributable=true;expect.quarantine_has_previous_record=true;expect.quarantine_previous_record_digest=expect.prepare_digest;expect.quarantine_has_head=true;expect.quarantine_head_digest=expect.successor_head_digest;expect.quarantine_reason=6;expect.quarantine_phase=2;expect.slot=17;expect.predecessor=pred.data();expect.predecessor_size=pe.encoded_size;expect.successor=succ.data();expect.successor_size=se.encoded_size;}
};
context_store_registry_lab_scope_value_v1 scope_value(const setup&s){return{s.expect.root_id,s.expect.path_policy_commitment,s.expect.registry_id,s.expect.registry_epoch};}
context_store_registry_lab_root_value_v1 root_value(const setup&s,context_store_registry_lab_root_state_v1 state){context_store_registry_lab_root_value_v1 v;v.scope=scope_value(s);v.store_uuid=s.expect.store_uuid;v.filesystem_uuid=s.expect.filesystem_uuid;v.mount_id=s.expect.mount_id;v.owner_uid=s.expect.owner_uid;v.lock_st_dev=s.expect.lock_st_dev;v.lock_st_ino=s.expect.lock_st_ino;v.state=state;v.initial_head_digest=s.expect.initial_head_digest;return v;}
context_store_registry_lab_head_value_v1 head_value(const setup&s,context_store_registry_lab_head_selection_v1 selection){context_store_registry_lab_head_value_v1 v;v.scope=scope_value(s);v.selection=selection;bool successor=selection==context_store_registry_lab_head_selection_v1::successor;const uint8_t*p=successor?s.expect.successor:s.expect.predecessor;size_t n=successor?s.expect.successor_size:s.expect.predecessor_size;std::copy_n(p,n,v.selected_envelope.bytes.begin());v.selected_envelope.size=n;v.selected_envelope_digest=successor?s.expect.successor_envelope_digest:s.expect.predecessor_envelope_digest;v.selected_high_water=s.expect.predecessor_high_water+(successor?1:0);v.selector_generation=successor?s.expect.successor_selector_generation:s.expect.predecessor_selector_generation;v.expected_head_digest=successor?s.expect.successor_head_digest:s.expect.initial_head_digest;if(successor){std::copy_n(s.expect.predecessor,s.expect.predecessor_size,v.predecessor_envelope.bytes.begin());v.predecessor_envelope.size=s.expect.predecessor_size;v.predecessor_envelope_digest=s.expect.predecessor_envelope_digest;v.predecessor_high_water=s.expect.predecessor_high_water;v.predecessor_selector_generation=s.expect.predecessor_selector_generation;}return v;}
context_store_registry_lab_prepare_value_v1 prepare_value(const setup&s){context_store_registry_lab_prepare_value_v1 v;v.scope=scope_value(s);v.attempt_id=s.expect.attempt_id;v.operation_commitment=s.expect.operation_commitment;v.predecessor_envelope_digest=s.expect.predecessor_envelope_digest;v.successor_envelope_digest=s.expect.successor_envelope_digest;v.initial_head_digest=s.expect.initial_head_digest;v.slot=s.expect.slot;v.predecessor_high_water=s.expect.predecessor_high_water;v.predecessor_selector_generation=s.expect.predecessor_selector_generation;v.successor_selector_generation=s.expect.successor_selector_generation;std::copy_n(s.expect.predecessor,s.expect.predecessor_size,v.predecessor.bytes.begin());v.predecessor.size=s.expect.predecessor_size;std::copy_n(s.expect.successor,s.expect.successor_size,v.successor.bytes.begin());v.successor.size=s.expect.successor_size;return v;}
context_store_registry_lab_close_value_v1 close_value_for(const setup&s,context_store_registry_lab_terminal_class_v1 terminal_class){context_store_registry_lab_close_value_v1 v;v.scope=scope_value(s);v.terminal_class=terminal_class;v.attempt_id=s.expect.attempt_id;v.operation_commitment=s.expect.operation_commitment;v.predecessor_envelope_digest=s.expect.predecessor_envelope_digest;v.successor_envelope_digest=s.expect.successor_envelope_digest;v.prepare_digest=s.expect.prepare_digest;v.head_digest=s.expect.successor_head_digest;v.slot=s.expect.slot;return v;}
context_store_registry_lab_abort_value_v1 abort_value_for(const setup&s,context_store_registry_lab_terminal_class_v1 terminal_class){context_store_registry_lab_abort_value_v1 v;v.scope=scope_value(s);v.terminal_class=terminal_class;v.attempt_id=s.expect.attempt_id;v.operation_commitment=s.expect.operation_commitment;v.predecessor_envelope_digest=s.expect.predecessor_envelope_digest;v.successor_envelope_digest=s.expect.successor_envelope_digest;v.prepare_digest=s.expect.prepare_digest;v.head_digest=s.expect.initial_head_digest;v.slot=s.expect.slot;return v;}
context_store_registry_lab_quarantine_value_v1 quarantine_value(const setup&s){context_store_registry_lab_quarantine_value_v1 v;v.scope=scope_value(s);v.event_id=s.expect.quarantine_event_id;v.attempt_id=s.expect.attempt_id;v.previous_record_digest=s.expect.quarantine_previous_record_digest;v.head_digest=s.expect.quarantine_head_digest;v.operation_commitment=s.expect.operation_commitment;v.slot=s.expect.slot;v.reason=s.expect.quarantine_reason;v.phase=s.expect.quarantine_phase;v.attributable=s.expect.quarantine_attributable;v.has_previous_record=s.expect.quarantine_has_previous_record;v.has_head=s.expect.quarantine_has_head;return v;}
using bytes=std::vector<uint8_t>;
bytes u(uint64_t v){bytes x;if(v<24)x.push_back(uint8_t(v));else if(v<=255)x={0x18,uint8_t(v)};else if(v<=65535)x={0x19,uint8_t(v>>8),uint8_t(v)};else if(v<=UINT32_MAX)x={0x1a,uint8_t(v>>24),uint8_t(v>>16),uint8_t(v>>8),uint8_t(v)};else{x={0x1b,uint8_t(v>>56),uint8_t(v>>48),uint8_t(v>>40),uint8_t(v>>32),uint8_t(v>>24),uint8_t(v>>16),uint8_t(v>>8),uint8_t(v)};}return x;}
bytes bs(const uint8_t*p,size_t n){auto h=u(n);h[0]|=0x40;h.insert(h.end(),p,p+n);return h;}template<size_t N>bytes bs(const std::array<uint8_t,N>&x){return bs(x.data(),x.size());}
bytes ts(const context_store_registered_id&i){auto h=u(i.size);h[0]|=0x60;h.insert(h.end(),i.bytes.begin(),i.bytes.begin()+i.size);return h;}
bytes mp(std::initializer_list<std::pair<uint64_t,bytes>>items){bytes out=u(items.size());out[0]|=0xa0;for(const auto&x:items){auto k=u(x.first);out.insert(out.end(),k.begin(),k.end());out.insert(out.end(),x.second.begin(),x.second.end());}return out;}
context_store_format_digest dh(const char*domain,const uint8_t*p,size_t n){bytes x(domain,domain+std::char_traits<char>::length(domain)+1);x.insert(x.end(),p,p+n);context_store_format_digest d{};assert(context_store_sha256_bounded(x.data(),x.size(),x.size(),d));return d;}
context_store_format_digest op_digest(const setup&s){auto body=mp({{0,bs(s.expect.root_id)},{1,bs(s.expect.path_policy_commitment)},{2,bs(s.expect.attempt_id)},{3,u(s.expect.slot)},{4,bs(s.expect.predecessor_envelope_digest)},{5,bs(s.expect.successor_envelope_digest)},{6,u(s.expect.predecessor_size)},{7,u(s.expect.successor_size)}});return dh("halofpx.registry-lab-operation.v1",body.data(),body.size());}
void refresh(setup&s){s.expect.predecessor_envelope_digest=dh("halofpx.registry-lab-registry-envelope.v1",s.pred.data(),s.expect.predecessor_size);s.expect.successor_envelope_digest=dh("halofpx.registry-lab-registry-envelope.v1",s.succ.data(),s.expect.successor_size);s.expect.operation_commitment=op_digest(s);}
bytes auth(const bytes&body,const setup&s,const char*domain){auto input=mp({{0,body},{1,ts(s.credential.key_id)},{2,u(1)},{3,u(s.credential.generation)}});context_store_format_digest dk{},tag{};constexpr char key_domain[]="halofpx.registry-lab-key.v1";bytes kd(reinterpret_cast<const uint8_t*>(key_domain),reinterpret_cast<const uint8_t*>(key_domain)+sizeof(key_domain));auto kid=ts(s.credential.key_id);kd.insert(kd.end(),kid.begin(),kid.end());auto gen=u(s.credential.generation);kd.insert(kd.end(),gen.begin(),gen.end());assert(context_store_hmac_sha256(s.secret.data(),32,kd.data(),kd.size(),dk));bytes msg(reinterpret_cast<const uint8_t*>(domain),reinterpret_cast<const uint8_t*>(domain)+std::char_traits<char>::length(domain)+1);msg.insert(msg.end(),input.begin(),input.end());assert(context_store_hmac_sha256(dk.data(),32,msg.data(),msg.size(),tag));return mp({{0,input},{1,bs(tag)}});}
context_store_format_digest witness_binding(const context_store_registry_lab_credential&c){constexpr char domain[]="halofpx.registry-lab-witness-credential.v1";bytes input(reinterpret_cast<const uint8_t*>(domain),reinterpret_cast<const uint8_t*>(domain)+sizeof(domain));auto key=ts(c.key_id);input.insert(input.end(),key.begin(),key.end());auto generation=u(c.generation);input.insert(input.end(),generation.begin(),generation.end());context_store_format_digest out{};assert(context_store_hmac_sha256(c.secret.data(),c.secret.size(),input.data(),input.size(),out));return out;}
bytes head_for(const setup&s,bool successor,uint64_t generation){auto*d=successor?&s.expect.successor_envelope_digest:&s.expect.predecessor_envelope_digest;size_t z=successor?s.expect.successor_size:s.expect.predecessor_size;auto body=mp({{0,u(1)},{1,u(0)},{2,u(1)},{3,bs(s.expect.root_id)},{4,bs(s.expect.path_policy_commitment)},{5,bs(*d)},{6,u(z)},{7,ts(s.expect.registry_id)},{8,u(s.expect.registry_epoch)},{9,u(s.expect.predecessor_high_water+(successor?1:0))},{10,u(generation)},{11,ts(s.credential.key_id)},{12,u(s.credential.generation)}});return auth(body,s,"halofpx.registry-lab-head-auth.v1");}
bytes prepare_for(const setup&s){auto body=mp({{0,u(1)},{1,u(0)},{2,u(2)},{3,bs(s.expect.root_id)},{4,bs(s.expect.path_policy_commitment)},{5,bs(s.expect.attempt_id)},{6,u(s.expect.slot)},{7,bs(s.expect.operation_commitment)},{8,u(s.expect.predecessor_size)},{9,bs(s.pred.data(),s.expect.predecessor_size)},{10,bs(s.expect.predecessor_envelope_digest)},{11,u(s.expect.successor_size)},{12,bs(s.succ.data(),s.expect.successor_size)},{13,bs(s.expect.successor_envelope_digest)},{14,u(1)},{15,bs(s.expect.initial_head_digest)},{16,bs(s.expect.initial_head_digest)}});return auth(body,s,"halofpx.registry-lab-prepare-auth.v1");}
bytes quarantine_unattributable_for(const setup&s){bytes nullv{0xf6};auto body=mp({{0,u(1)},{1,u(0)},{2,u(5)},{3,bs(s.expect.root_id)},{4,bs(s.expect.path_policy_commitment)},{5,bs(s.expect.quarantine_event_id)},{6,nullv},{7,nullv},{8,u(s.expect.quarantine_reason)},{9,u(s.expect.quarantine_phase)},{10,nullv},{11,nullv},{12,nullv}});return auth(body,s,"halofpx.registry-lab-quarantine-auth.v1");}
bytes quarantine_unattributable_head_for(const setup&s){bytes nullv{0xf6};auto body=mp({{0,u(1)},{1,u(0)},{2,u(5)},{3,bs(s.expect.root_id)},{4,bs(s.expect.path_policy_commitment)},{5,bs(s.expect.quarantine_event_id)},{6,nullv},{7,nullv},{8,u(s.expect.quarantine_reason)},{9,u(0)},{10,nullv},{11,bs(s.expect.initial_head_digest)},{12,nullv}});return auth(body,s,"halofpx.registry-lab-quarantine-auth.v1");}
void retag(std::vector<uint8_t>&v,const setup&s,const char*domain){context_store_format_digest dk{},tag{};std::array<uint8_t,256>kdf{};size_t n=0;auto put=[&](const void*p,size_t z){std::copy_n(static_cast<const uint8_t*>(p),z,kdf.begin()+n);n+=z;};constexpr char kd[]="halofpx.registry-lab-key.v1";put(kd,sizeof(kd));uint8_t t=0x70;put(&t,1);put(s.credential.key_id.bytes.data(),16);uint8_t g=13;put(&g,1);assert(context_store_hmac_sha256(s.secret.data(),32,kdf.data(),n,dk));std::vector<uint8_t>msg;msg.insert(msg.end(),domain,domain+std::char_traits<char>::length(domain)+1);msg.insert(msg.end(),v.begin()+2,v.end()-35);assert(context_store_hmac_sha256(dk.data(),32,msg.data(),msg.size(),tag));std::copy(tag.begin(),tag.end(),v.end()-32);}
bool replace(std::vector<uint8_t>&v,std::initializer_list<uint8_t>from,std::initializer_list<uint8_t>to){auto p=std::search(v.begin(),v.end(),from.begin(),from.end());if(p==v.end())return false;auto at=size_t(p-v.begin());v.erase(v.begin()+at,v.begin()+at+from.size());v.insert(v.begin()+at,to.begin(),to.end());return true;}
}
int main(int argc,char**argv){assert(argc==2);std::ifstream f(argv[1],std::ios::binary);std::string json((std::istreambuf_iterator<char>(f)),{});setup s;
context_store_format_digest registry_digest_output{};registry_digest_output.fill(0xa5);const auto registry_digest_before=registry_digest_output;assert(!context_store_registry_lab_registry_envelope_digest_v1(nullptr,1,registry_digest_output)&&registry_digest_output==registry_digest_before);assert(!context_store_registry_lab_registry_envelope_digest_v1(s.pred.data(),0,registry_digest_output)&&registry_digest_output==registry_digest_before);assert(!context_store_registry_lab_registry_envelope_digest_v1(s.pred.data(),1025,registry_digest_output)&&registry_digest_output==registry_digest_before);assert(context_store_registry_lab_registry_envelope_digest_v1(s.pred.data(),s.expect.predecessor_size,registry_digest_output));assert(registry_digest_output==digest(value(json,"predecessor_registry_envelope_digest_hex").c_str()));auto changed_registry=s.pred;changed_registry[0]^=1;context_store_format_digest changed_registry_digest{};assert(context_store_registry_lab_registry_envelope_digest_v1(changed_registry.data(),s.expect.predecessor_size,changed_registry_digest)&&changed_registry_digest!=registry_digest_output);
auto package=hex_bytes(value(json,"credential_package_hex"));context_store_registry_lab_credential parsed;assert(context_store_registry_lab_parse_credential_v1(package.data(),package.size(),parsed));assert(parsed.generation==13&&parsed.key_id.size==16&&parsed.secret==s.secret);context_store_registry_lab_credential moved(std::move(parsed));assert(parsed.generation==0&&!std::any_of(parsed.secret.begin(),parsed.secret.end(),[](uint8_t b){return b!=0;}));assert(moved.generation==13&&moved.secret==s.secret);parsed=std::move(moved);for(size_t i=0;i<package.size();++i){auto x=package;x[i]^=1;context_store_registry_lab_credential ignored;assert(!context_store_registry_lab_parse_credential_v1(x.data(),x.size(),ignored)||ignored.secret!=s.secret||ignored.generation!=13||!std::equal(ignored.key_id.bytes.begin(),ignored.key_id.bytes.begin()+ignored.key_id.size,s.credential.key_id.bytes.begin(),s.credential.key_id.bytes.begin()+s.credential.key_id.size));}
context_store_registry_lab_credential seeded;seeded.key_id=id("seeded");seeded.generation=99;seeded.secret.fill(0xaa);assert(!context_store_registry_lab_parse_credential_v1(nullptr,0,seeded));assert(!seeded.generation&&!seeded.key_id.size&&!std::any_of(seeded.secret.begin(),seeded.secret.end(),[](uint8_t b){return b!=0;}));
alignas(context_store_registry_lab_credential) std::array<std::byte,sizeof(context_store_registry_lab_credential)> storage{};auto*placed=new(storage.data()) context_store_registry_lab_credential;placed->key_id=id("placed");placed->generation=7;placed->secret.fill(0x5a);auto*secret_address=placed->secret.data();placed->~context_store_registry_lab_credential();assert(std::all_of(secret_address,secret_address+32,[](uint8_t b){return b==0;}));
context_store_registry_lab_credential overwrite_source;overwrite_source.key_id=id("overwrite-source");overwrite_source.generation=8;overwrite_source.secret.fill(0x6b);context_store_registry_lab_credential overwrite_destination;overwrite_destination.key_id=id("overwrite-destination");overwrite_destination.generation=9;overwrite_destination.secret.fill(0xa7);overwrite_destination=std::move(overwrite_source);assert(overwrite_destination.generation==8&&std::all_of(overwrite_destination.secret.begin(),overwrite_destination.secret.end(),[](uint8_t b){return b==0x6b;})&&!overwrite_source.generation&&std::all_of(overwrite_source.secret.begin(),overwrite_source.secret.end(),[](uint8_t b){return b==0;}));
std::array<uint8_t,16>fs{},sub{};fs.fill(0x44);sub.fill(0x45);context_store_format_digest path{};const std::string parent="/mnt/halofpx-l05o-loop",root=parent+"/run-001";assert(context_store_registry_lab_path_policy_v1((const uint8_t*)parent.data(),parent.size(),(const uint8_t*)root.data(),root.size(),fs,sub,731,2049,1000,path));assert(path==s.expect.path_policy_commitment);
struct row{const char*name;context_store_registry_lab_kind kind;const char*digest_hex;};const row rows[]={
{"root_initializing",context_store_registry_lab_kind::root,"902e919dd48e0f0ceece0156f09806edd46d8e68a4c2eab7c34225334c2f9fa8"},{"root_initialized",context_store_registry_lab_kind::root,"6ce909a8b9985fcaf152ecd1c6ffb7fa9217041928f116bc01409d72e60ae39c"},{"head_initial",context_store_registry_lab_kind::head,"93ea1f031d4ec2827bc28535d56f2a0a1f6efb49ecff9ed763cf03bced0c0d82"},{"prepare",context_store_registry_lab_kind::prepare,"9ea5eced3354b6a90ca306361568de879d5ebfc9effd63de6f73629c04baa8fa"},{"head_successor",context_store_registry_lab_kind::head,"d3d372ef42c5254a2baca52ba35cae46899cdf0e464396e3fa272ffc238a309b"},{"close",context_store_registry_lab_kind::close,"526e0025c5b5833fc2d731473ca6db3175dc25edc37996f60827a4f65151a1e8"},{"abort",context_store_registry_lab_kind::abort_record,"0880c4e52c10a7d9da305199f591d0b228e5e7e6c7c86d4374b596966f4717ef"},{"quarantine",context_store_registry_lab_kind::quarantine,"c77c94ec11040a9379533dbd8c74ba3bf50ff3436e34d2a593c0f2f3106e21a4"}};
for(const auto&r:rows){auto v=fixture(json,r.name);auto good=context_store_registry_lab_verify_v1(r.kind,v.data(),v.size(),s.credential,s.expect);assert(good.authenticated()&&good.content_digest==digest(r.digest_hex));for(size_t cut=0;cut<v.size();++cut)assert(!context_store_registry_lab_verify_v1(r.kind,v.data(),cut,s.credential,s.expect).authenticated());for(size_t i=0;i<v.size();++i){auto x=v;x[i]^=1;assert(!context_store_registry_lab_verify_v1(r.kind,x.data(),x.size(),s.credential,s.expect).authenticated());}auto trailing=v;trailing.push_back(0);assert(!context_store_registry_lab_verify_v1(r.kind,trailing.data(),trailing.size(),s.credential,s.expect).authenticated());}
auto golden_predecessor_head=fixture(json,"head_initial");auto golden_successor_head=fixture(json,"head_successor");auto golden_prepare=fixture(json,"prepare");
auto wrong_prepare_digest=s.expect;wrong_prepare_digest.prepare_digest[0]^=1;assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::prepare,golden_prepare.data(),golden_prepare.size(),s.credential,wrong_prepare_digest).authenticated());
auto root_initializing_value=root_value(s,context_store_registry_lab_root_state_v1::initializing),root_initialized_value=root_value(s,context_store_registry_lab_root_state_v1::initialized);root_initializing_value.initial_head_digest={};auto head_predecessor_value=head_value(s,context_store_registry_lab_head_selection_v1::predecessor),head_successor_value=head_value(s,context_store_registry_lab_head_selection_v1::successor);auto prepare_typed_value=prepare_value(s);auto close_value=close_value_for(s,context_store_registry_lab_terminal_class_v1::normal);auto abort_value=abort_value_for(s,context_store_registry_lab_terminal_class_v1::recovered);auto quarantine_typed_value=quarantine_value(s);
context_store_registry_lab_root_witness root_initializing_witness,root_initialized_witness;assert(context_store_registry_lab_admit_root_v1(root_initializing_value,s.credential,{},root_initializing_witness));
context_store_registry_lab_credential witness_destination_credential;witness_destination_credential.key_id=id("witness-destination");witness_destination_credential.generation=21;witness_destination_credential.secret.fill(0x31);context_store_registry_lab_credential witness_source_credential;witness_source_credential.key_id=id("witness-source");witness_source_credential.generation=22;witness_source_credential.secret.fill(0x32);auto destination_binding=witness_binding(witness_destination_credential),source_binding=witness_binding(witness_source_credential);alignas(context_store_registry_lab_root_witness) std::array<std::byte,sizeof(context_store_registry_lab_root_witness)> destination_witness_storage{},source_witness_storage{};auto*destination_witness=new(destination_witness_storage.data()) context_store_registry_lab_root_witness;auto*source_witness=new(source_witness_storage.data()) context_store_registry_lab_root_witness;assert(context_store_registry_lab_admit_root_v1(root_initializing_value,witness_destination_credential,{},*destination_witness)&&context_store_registry_lab_admit_root_v1(root_initializing_value,witness_source_credential,{},*source_witness));*destination_witness=std::move(*source_witness);auto destination_bytes=reinterpret_cast<const uint8_t*>(destination_witness_storage.data());auto source_bytes=reinterpret_cast<const uint8_t*>(source_witness_storage.data());assert(std::search(destination_bytes,destination_bytes+destination_witness_storage.size(),destination_binding.begin(),destination_binding.end())==destination_bytes+destination_witness_storage.size());assert(std::search(source_bytes,source_bytes+source_witness_storage.size(),source_binding.begin(),source_binding.end())==source_bytes+source_witness_storage.size());destination_witness->~context_store_registry_lab_root_witness();assert(std::search(destination_bytes,destination_bytes+destination_witness_storage.size(),source_binding.begin(),source_binding.end())==destination_bytes+destination_witness_storage.size());source_witness->~context_store_registry_lab_root_witness();
context_store_registry_lab_root_evidence_v1 root_evidence;root_evidence.authenticated_head=golden_predecessor_head.data();root_evidence.authenticated_head_size=golden_predecessor_head.size();std::copy_n(s.expect.predecessor,s.expect.predecessor_size,root_evidence.selected_envelope.bytes.begin());root_evidence.selected_envelope.size=s.expect.predecessor_size;root_evidence.selected_envelope_digest=s.expect.predecessor_envelope_digest;root_evidence.selected_high_water=s.expect.predecessor_high_water;root_evidence.selector_generation=s.expect.predecessor_selector_generation;assert(context_store_registry_lab_admit_root_v1(root_initialized_value,s.credential,root_evidence,root_initialized_witness));
context_store_registry_lab_head_witness head_predecessor_witness,head_successor_witness;assert(context_store_registry_lab_admit_head_v1(head_predecessor_value,s.credential,head_predecessor_witness)&&context_store_registry_lab_admit_head_v1(head_successor_value,s.credential,head_successor_witness));context_store_registry_lab_prepare_evidence_v1 prepare_evidence{golden_predecessor_head.data(),golden_predecessor_head.size()};context_store_registry_lab_prepare_witness prepare_witness;assert(context_store_registry_lab_admit_prepare_v1(prepare_typed_value,s.credential,prepare_evidence,prepare_witness));
std::array<uint8_t,context_store_registry_lab_wire_max_bytes> preknowledge_free_prepare{};size_t preknowledge_free_prepare_size=0;auto preknowledge_free_result=context_store_registry_lab_encode_prepare_v1(prepare_typed_value,s.credential,prepare_witness,preknowledge_free_prepare.data(),preknowledge_free_prepare.size(),preknowledge_free_prepare_size);assert(preknowledge_free_result.authenticated()&&preknowledge_free_prepare_size==golden_prepare.size()&&std::equal(golden_prepare.begin(),golden_prepare.end(),preknowledge_free_prepare.begin()));auto independent_prepare_digest=dh("halofpx.registry-lab-prepare.v1",preknowledge_free_prepare.data(),preknowledge_free_prepare_size);assert(preknowledge_free_result.content_digest==independent_prepare_digest&&preknowledge_free_result.content_digest==s.expect.prepare_digest);close_value.prepare_digest=preknowledge_free_result.content_digest;abort_value.prepare_digest=preknowledge_free_result.content_digest;
auto predecessor_with_successor_only=head_predecessor_value;predecessor_with_successor_only.predecessor_envelope.size=1;context_store_registry_lab_head_witness successor_only_rejected;assert(!context_store_registry_lab_admit_head_v1(predecessor_with_successor_only,s.credential,successor_only_rejected));predecessor_with_successor_only=head_predecessor_value;predecessor_with_successor_only.predecessor_envelope.bytes[0]=1;assert(!context_store_registry_lab_admit_head_v1(predecessor_with_successor_only,s.credential,successor_only_rejected));predecessor_with_successor_only=head_predecessor_value;predecessor_with_successor_only.predecessor_envelope_digest[0]=1;assert(!context_store_registry_lab_admit_head_v1(predecessor_with_successor_only,s.credential,successor_only_rejected));predecessor_with_successor_only=head_predecessor_value;predecessor_with_successor_only.predecessor_high_water=1;assert(!context_store_registry_lab_admit_head_v1(predecessor_with_successor_only,s.credential,successor_only_rejected));predecessor_with_successor_only=head_predecessor_value;predecessor_with_successor_only.predecessor_selector_generation=1;assert(!context_store_registry_lab_admit_head_v1(predecessor_with_successor_only,s.credential,successor_only_rejected));
context_store_registry_lab_close_evidence_v1 close_evidence{prepare_typed_value,golden_predecessor_head.data(),golden_predecessor_head.size(),golden_successor_head.data(),golden_successor_head.size(),golden_prepare.data(),golden_prepare.size()};context_store_registry_lab_close_witness close_witness;assert(context_store_registry_lab_admit_close_v1(close_value,s.credential,close_evidence,close_witness));context_store_registry_lab_abort_evidence_v1 abort_evidence{prepare_typed_value,golden_predecessor_head.data(),golden_predecessor_head.size(),golden_prepare.data(),golden_prepare.size()};context_store_registry_lab_abort_witness abort_witness;assert(context_store_registry_lab_admit_abort_v1(abort_value,s.credential,abort_evidence,abort_witness));
context_store_registry_lab_quarantine_evidence_v1 quarantine_evidence{&prepare_typed_value,golden_predecessor_head.data(),golden_predecessor_head.size(),golden_successor_head.data(),golden_successor_head.size(),golden_prepare.data(),golden_prepare.size()};context_store_registry_lab_quarantine_witness quarantine_witness;assert(context_store_registry_lab_admit_quarantine_v1(quarantine_typed_value,s.credential,quarantine_evidence,quarantine_witness));
auto exact_encode=[&](const char*fixture_name,auto invoke,size_t maximum){auto expected=fixture(json,fixture_name);std::vector<uint8_t>out(maximum,0xa5);size_t n=777;auto result=invoke(out.data(),out.size(),n);assert(result.authenticated()&&n==expected.size()&&std::equal(expected.begin(),expected.end(),out.begin()));auto unchanged=out;size_t old=991;assert(!invoke(out.data(),expected.size()-1,old).authenticated()&&old==991&&out==unchanged);};
exact_encode("root_initializing",[&](uint8_t*o,size_t z,size_t&n){return context_store_registry_lab_encode_root_v1(root_initializing_value,s.credential,root_initializing_witness,o,z,n);},1024);exact_encode("root_initialized",[&](uint8_t*o,size_t z,size_t&n){return context_store_registry_lab_encode_root_v1(root_initialized_value,s.credential,root_initialized_witness,o,z,n);},1024);exact_encode("head_initial",[&](uint8_t*o,size_t z,size_t&n){return context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,o,z,n);},1024);exact_encode("head_successor",[&](uint8_t*o,size_t z,size_t&n){return context_store_registry_lab_encode_head_v1(head_successor_value,s.credential,head_successor_witness,o,z,n);},1024);exact_encode("prepare",[&](uint8_t*o,size_t z,size_t&n){return context_store_registry_lab_encode_prepare_v1(prepare_typed_value,s.credential,prepare_witness,o,z,n);},4096);exact_encode("close",[&](uint8_t*o,size_t z,size_t&n){return context_store_registry_lab_encode_close_v1(close_value,s.credential,close_witness,o,z,n);},1024);exact_encode("abort",[&](uint8_t*o,size_t z,size_t&n){return context_store_registry_lab_encode_abort_v1(abort_value,s.credential,abort_witness,o,z,n);},1024);exact_encode("quarantine",[&](uint8_t*o,size_t z,size_t&n){return context_store_registry_lab_encode_quarantine_v1(quarantine_typed_value,s.credential,quarantine_witness,o,z,n);},1024);
std::array<uint8_t,4096> alias_output{};alias_output.fill(0x4d);auto encoded_size_alias_rejected=[&](auto invoke,auto&object){auto before=alias_output;auto&aliased=*reinterpret_cast<size_t*>(&object);auto prior=aliased;assert(!invoke(aliased).authenticated()&&aliased==prior&&alias_output==before);};
auto root_invoke=[&](size_t&n){return context_store_registry_lab_encode_root_v1(root_initializing_value,s.credential,root_initializing_witness,alias_output.data(),1024,n);};encoded_size_alias_rejected(root_invoke,root_initializing_value);encoded_size_alias_rejected(root_invoke,root_initializing_witness);
auto head_invoke=[&](size_t&n){return context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,alias_output.data(),1024,n);};encoded_size_alias_rejected(head_invoke,head_predecessor_value);encoded_size_alias_rejected(head_invoke,head_predecessor_witness);
auto prepare_invoke=[&](size_t&n){return context_store_registry_lab_encode_prepare_v1(prepare_typed_value,s.credential,prepare_witness,alias_output.data(),alias_output.size(),n);};encoded_size_alias_rejected(prepare_invoke,prepare_typed_value);encoded_size_alias_rejected(prepare_invoke,prepare_witness);
auto close_invoke=[&](size_t&n){return context_store_registry_lab_encode_close_v1(close_value,s.credential,close_witness,alias_output.data(),1024,n);};encoded_size_alias_rejected(close_invoke,close_value);encoded_size_alias_rejected(close_invoke,close_witness);
auto abort_invoke=[&](size_t&n){return context_store_registry_lab_encode_abort_v1(abort_value,s.credential,abort_witness,alias_output.data(),1024,n);};encoded_size_alias_rejected(abort_invoke,abort_value);encoded_size_alias_rejected(abort_invoke,abort_witness);
auto quarantine_invoke=[&](size_t&n){return context_store_registry_lab_encode_quarantine_v1(quarantine_typed_value,s.credential,quarantine_witness,alias_output.data(),1024,n);};encoded_size_alias_rejected(quarantine_invoke,quarantine_typed_value);encoded_size_alias_rejected(quarantine_invoke,quarantine_witness);
auto exact_head=fixture(json,"head_initial");std::vector<uint8_t>exact_boundary(exact_head.size(),0x3a);size_t exact_boundary_size=0;assert(context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,exact_boundary.data(),exact_boundary.size(),exact_boundary_size).authenticated()&&exact_boundary==exact_head);
auto saved_pred=s.pred[0];s.pred[0]^=1;std::array<uint8_t,1024>owned_output{};size_t owned_size=0;assert(context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,owned_output.data(),owned_output.size(),owned_size).authenticated()&&owned_size==exact_head.size()&&std::equal(exact_head.begin(),exact_head.end(),owned_output.begin()));s.pred[0]=saved_pred;
std::array<uint8_t,1025>too_large{};too_large.fill(0x5c);auto too_large_before=too_large;size_t untouched=44;assert(!context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,too_large.data(),too_large.size(),untouched).authenticated()&&too_large==too_large_before&&untouched==44);
auto secret_before=s.credential.secret;assert(!context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,reinterpret_cast<uint8_t*>(&s.credential),1,untouched).authenticated()&&s.credential.secret==secret_before);
assert(!context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,reinterpret_cast<uint8_t*>(&head_predecessor_witness),1,untouched).authenticated());assert(context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,owned_output.data(),owned_output.size(),owned_size).authenticated());
assert(!context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,reinterpret_cast<uint8_t*>(UINTPTR_MAX-3),8,untouched).authenticated());
alignas(size_t) std::array<uint8_t,1024>aliased_size_output{};aliased_size_output.fill(0x2e);auto aliased_size_before=aliased_size_output;auto&aliased_size=*reinterpret_cast<size_t*>(aliased_size_output.data());assert(!context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,aliased_size_output.data(),aliased_size_output.size(),aliased_size).authenticated()&&aliased_size_output==aliased_size_before);
context_store_registry_lab_head_witness invalid_witness;std::array<uint8_t,1024>invalid_output{};invalid_output.fill(0x7d);auto invalid_before=invalid_output;assert(!context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,invalid_witness,invalid_output.data(),invalid_output.size(),untouched).authenticated()&&invalid_output==invalid_before);
context_store_registry_lab_credential invalid_credential;assert(!context_store_registry_lab_encode_head_v1(head_predecessor_value,invalid_credential,head_predecessor_witness,invalid_output.data(),invalid_output.size(),untouched).authenticated()&&invalid_output==invalid_before);
// The internal halofpx.registry-lab-witness-credential.v1 domain binds admission to the exact master secret.
context_store_registry_lab_credential wrong_master;wrong_master.key_id=s.credential.key_id;wrong_master.generation=s.credential.generation;wrong_master.secret.fill(0x45);assert(!context_store_registry_lab_encode_head_v1(head_predecessor_value,wrong_master,head_predecessor_witness,invalid_output.data(),invalid_output.size(),untouched).authenticated()&&invalid_output==invalid_before);
std::array<uint8_t,1024>post_success_output{};size_t post_success_size=0;assert(context_store_registry_lab_encode_head_v1(head_predecessor_value,s.credential,head_predecessor_witness,post_success_output.data(),post_success_output.size(),post_success_size).authenticated());auto post_success_before=post_success_output;auto post_success_size_before=post_success_size;auto changed_head_value=head_predecessor_value;changed_head_value.selector_generation++;assert(!context_store_registry_lab_encode_head_v1(changed_head_value,s.credential,head_predecessor_witness,post_success_output.data(),post_success_output.size(),post_success_size).authenticated()&&post_success_output==post_success_before&&post_success_size==post_success_size_before);
auto root_only=s.expect;root_only.predecessor=nullptr;root_only.predecessor_size=0;root_only.successor=nullptr;root_only.successor_size=0;root_only.predecessor_envelope_digest={};root_only.successor_envelope_digest={};root_only.prepare_digest={};root_only.operation_commitment={};root_only.attempt_id={};root_only.quarantine_event_id={};root_only.initial_head_digest={};auto initializing=fixture(json,"root_initializing");assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::root,initializing.data(),initializing.size(),s.credential,root_only).authenticated());
auto head_only=s.expect;head_only.successor=nullptr;head_only.successor_size=0;head_only.successor_envelope_digest={};head_only.successor_selector_generation=0;head_only.prepare_digest={};head_only.operation_commitment={};head_only.attempt_id={};head_only.quarantine_event_id={};auto initial=fixture(json,"head_initial");assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,initial.data(),initial.size(),s.credential,head_only).authenticated());
for(auto field:std::array<int,3>{0,1,2}){auto zero=fixture(json,"root_initializing");bool changed=field==0?replace(zero,{0x08,0x19,0x02,0xdb},{0x08,0x00}):field==1?replace(zero,{0x10,0x19,0x08,0x01},{0x10,0x00}):replace(zero,{0x11,0x1a,0x00,0x0f,0x12,0x06},{0x11,0x00});assert(changed);retag(zero,s,"halofpx.registry-lab-root-auth.v1");auto expected=s.expect;if(field==0)expected.mount_id=0;else if(field==1)expected.lock_st_dev=0;else expected.lock_st_ino=0;assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::root,zero.data(),zero.size(),s.credential,expected).authenticated());}
auto head=fixture(json,"head_initial");const std::array<uint8_t,2> selector_generation={0x0a,0x01};auto p=std::search(head.begin(),head.end(),selector_generation.begin(),selector_generation.end());assert(p!=head.end());p[1]=3;retag(head,s,"halofpx.registry-lab-head-auth.v1");auto alternate=s.expect;alternate.predecessor_selector_generation=3;alternate.successor_selector_generation=4;assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,head.data(),head.size(),s.credential,alternate).authenticated());
auto invalid=s.expect;invalid.predecessor_size=0;assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,head.data(),head.size(),s.credential,invalid).authenticated());invalid=s.expect;invalid.registry_id={};assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,head.data(),head.size(),s.credential,invalid).authenticated());
auto wrong=s.expect;wrong.path_policy_commitment[0]^=1;auto q=fixture(json,"quarantine");assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,q.data(),q.size(),s.credential,wrong).authenticated());
auto qreason=q;assert(replace(qreason,{0x08,0x06,0x09,0x02},{0x08,0x07,0x09,0x02}));retag(qreason,s,"halofpx.registry-lab-quarantine-auth.v1");assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,qreason.data(),qreason.size(),s.credential,s.expect).authenticated());auto qexpect=s.expect;qexpect.quarantine_reason=7;assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,qreason.data(),qreason.size(),s.credential,qexpect).authenticated());
auto close=fixture(json,"close");assert(replace(close,{0x0b,0x02,0x0c,0x00},{0x0b,0x01,0x0c,0x00}));retag(close,s,"halofpx.registry-lab-close-auth.v1");assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::close,close.data(),close.size(),s.credential,s.expect).authenticated());
auto recovery=fixture(json,"close");assert(replace(recovery,{0x0b,0x02,0x0c,0x00},{0x0b,0x02,0x0c,0x01}));retag(recovery,s,"halofpx.registry-lab-close-auth.v1");assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::close,recovery.data(),recovery.size(),s.credential,s.expect).authenticated());
setup arbitrary(123);refresh(arbitrary);arbitrary.expect.predecessor_selector_generation=7;arbitrary.expect.successor_selector_generation=8;auto arbitrary_head=head_for(arbitrary,false,7);assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,arbitrary_head.data(),arbitrary_head.size(),arbitrary.credential,arbitrary.expect).authenticated());auto arbitrary_successor=head_for(arbitrary,true,8);assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,arbitrary_successor.data(),arbitrary_successor.size(),arbitrary.credential,arbitrary.expect).authenticated());
arbitrary.expect.initial_head_digest=dh("halofpx.registry-lab-head.v1",arbitrary_head.data(),arbitrary_head.size());arbitrary.expect.successor_head_digest=dh("halofpx.registry-lab-head.v1",arbitrary_successor.data(),arbitrary_successor.size());auto arbitrary_prepare=prepare_for(arbitrary);arbitrary.expect.prepare_digest=dh("halofpx.registry-lab-prepare.v1",arbitrary_prepare.data(),arbitrary_prepare.size());
auto arbitrary_pred_value=head_value(arbitrary,context_store_registry_lab_head_selection_v1::predecessor),arbitrary_succ_value=head_value(arbitrary,context_store_registry_lab_head_selection_v1::successor);auto arbitrary_prepare_value=prepare_value(arbitrary);context_store_registry_lab_head_witness arbitrary_pred_witness,arbitrary_succ_witness;assert(context_store_registry_lab_admit_head_v1(arbitrary_pred_value,arbitrary.credential,arbitrary_pred_witness)&&context_store_registry_lab_admit_head_v1(arbitrary_succ_value,arbitrary.credential,arbitrary_succ_witness));context_store_registry_lab_prepare_evidence_v1 arbitrary_pred_evidence{arbitrary_head.data(),arbitrary_head.size()};context_store_registry_lab_prepare_witness arbitrary_prepare_witness;assert(context_store_registry_lab_admit_prepare_v1(arbitrary_prepare_value,arbitrary.credential,arbitrary_pred_evidence,arbitrary_prepare_witness));auto arbitrary_close_value=close_value_for(arbitrary,context_store_registry_lab_terminal_class_v1::recovered);context_store_registry_lab_close_evidence_v1 arbitrary_close_evidence{arbitrary_prepare_value,arbitrary_head.data(),arbitrary_head.size(),arbitrary_successor.data(),arbitrary_successor.size(),arbitrary_prepare.data(),arbitrary_prepare.size()};context_store_registry_lab_close_witness arbitrary_close_witness;assert(context_store_registry_lab_admit_close_v1(arbitrary_close_value,arbitrary.credential,arbitrary_close_evidence,arbitrary_close_witness));
std::array<uint8_t,4096> arbitrary_encoded{};size_t arbitrary_size=0;assert(context_store_registry_lab_encode_head_v1(arbitrary_pred_value,arbitrary.credential,arbitrary_pred_witness,arbitrary_encoded.data(),1024,arbitrary_size).authenticated()&&arbitrary_size==arbitrary_head.size()&&std::equal(arbitrary_head.begin(),arbitrary_head.end(),arbitrary_encoded.begin()));assert(context_store_registry_lab_encode_head_v1(arbitrary_succ_value,arbitrary.credential,arbitrary_succ_witness,arbitrary_encoded.data(),1024,arbitrary_size).authenticated()&&arbitrary_size==arbitrary_successor.size()&&std::equal(arbitrary_successor.begin(),arbitrary_successor.end(),arbitrary_encoded.begin()));assert(context_store_registry_lab_encode_prepare_v1(arbitrary_prepare_value,arbitrary.credential,arbitrary_prepare_witness,arbitrary_encoded.data(),arbitrary_encoded.size(),arbitrary_size).authenticated()&&arbitrary_size==arbitrary_prepare.size()&&std::equal(arbitrary_prepare.begin(),arbitrary_prepare.end(),arbitrary_encoded.begin()));assert(context_store_registry_lab_encode_close_v1(arbitrary_close_value,arbitrary.credential,arbitrary_close_witness,arbitrary_encoded.data(),1024,arbitrary_size).authenticated());
setup boundary(UINT64_MAX-1);refresh(boundary);boundary.expect.predecessor_selector_generation=UINT64_MAX-1;boundary.expect.successor_selector_generation=UINT64_MAX;auto boundary_head=head_for(boundary,false,UINT64_MAX-1);auto boundary_successor=head_for(boundary,true,UINT64_MAX);boundary.expect.initial_head_digest=dh("halofpx.registry-lab-head.v1",boundary_head.data(),boundary_head.size());boundary.expect.successor_head_digest=dh("halofpx.registry-lab-head.v1",boundary_successor.data(),boundary_successor.size());auto boundary_pred_value=head_value(boundary,context_store_registry_lab_head_selection_v1::predecessor),boundary_succ_value=head_value(boundary,context_store_registry_lab_head_selection_v1::successor);context_store_registry_lab_head_witness boundary_pred_witness,boundary_succ_witness;assert(context_store_registry_lab_admit_head_v1(boundary_pred_value,boundary.credential,boundary_pred_witness)&&context_store_registry_lab_admit_head_v1(boundary_succ_value,boundary.credential,boundary_succ_witness));assert(context_store_registry_lab_encode_head_v1(boundary_pred_value,boundary.credential,boundary_pred_witness,arbitrary_encoded.data(),1024,arbitrary_size).authenticated()&&context_store_registry_lab_encode_head_v1(boundary_succ_value,boundary.credential,boundary_succ_witness,arbitrary_encoded.data(),1024,arbitrary_size).authenticated());
setup mismatch;setup observed(55);refresh(observed);auto observed_head=head_for(observed,false,1);mismatch.expect.initial_head_digest=dh("halofpx.registry-lab-head.v1",observed_head.data(),observed_head.size());auto mismatch_prepare=prepare_for(mismatch);mismatch.expect.prepare_digest=dh("halofpx.registry-lab-prepare.v1",mismatch_prepare.data(),mismatch_prepare.size());auto mismatch_prepare_value=prepare_value(mismatch);auto mismatch_terminal_value=abort_value_for(mismatch,context_store_registry_lab_terminal_class_v1::normal);context_store_registry_lab_abort_evidence_v1 mismatch_evidence{};mismatch_evidence.transition=mismatch_prepare_value;mismatch_evidence.prepare=mismatch_prepare.data();mismatch_evidence.prepare_size=mismatch_prepare.size();mismatch_evidence.observed_head=observed_head.data();mismatch_evidence.observed_head_size=observed_head.size();mismatch_evidence.observed_resolved=observed.pred.data();mismatch_evidence.observed_resolved_size=observed.expect.predecessor_size;context_store_registry_lab_abort_witness mismatch_witness;assert(context_store_registry_lab_admit_abort_v1(mismatch_terminal_value,mismatch.credential,mismatch_evidence,mismatch_witness));assert(context_store_registry_lab_encode_abort_v1(mismatch_terminal_value,mismatch.credential,mismatch_witness,arbitrary_encoded.data(),1024,arbitrary_size).authenticated());auto not_mismatch=mismatch_evidence;not_mismatch.observed_resolved=mismatch.pred.data();not_mismatch.observed_resolved_size=mismatch.expect.predecessor_size;context_store_registry_lab_abort_witness false_mismatch_witness;assert(!context_store_registry_lab_admit_abort_v1(mismatch_terminal_value,mismatch.credential,not_mismatch,false_mismatch_witness));
assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,arbitrary_head.data(),arbitrary_head.size(),s.credential,s.expect).authenticated());
setup skipped(40,2);refresh(skipped);auto repaired_h_plus_two=prepare_for(skipped);assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::prepare,repaired_h_plus_two.data(),repaired_h_plus_two.size(),skipped.credential,skipped.expect).authenticated());
setup wrong_operation;refresh(wrong_operation);wrong_operation.expect.operation_commitment[0]^=1;auto repaired_wrong_operation=prepare_for(wrong_operation);assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::prepare,repaired_wrong_operation.data(),repaired_wrong_operation.size(),wrong_operation.credential,wrong_operation.expect).authenticated());
setup unattributable;unattributable.expect.quarantine_attributable=false;unattributable.expect.quarantine_has_previous_record=false;unattributable.expect.quarantine_has_head=false;auto qnull=quarantine_unattributable_for(unattributable);assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,qnull.data(),qnull.size(),unattributable.credential,unattributable.expect).authenticated());assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,q.data(),q.size(),unattributable.credential,unattributable.expect).authenticated());assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,qnull.data(),qnull.size(),s.credential,s.expect).authenticated());
auto uh=quarantine_value(s);uh.attributable=false;uh.has_previous_record=false;uh.has_head=true;uh.attempt_id={};uh.previous_record_digest={};uh.operation_commitment={};uh.slot=0;uh.phase=0;uh.head_digest=s.expect.initial_head_digest;
context_store_registry_lab_quarantine_evidence_v1 uh_evidence{};uh_evidence.standalone_predecessor_head_value=&head_predecessor_value;uh_evidence.predecessor_head=golden_predecessor_head.data();uh_evidence.predecessor_head_size=golden_predecessor_head.size();context_store_registry_lab_quarantine_witness uh_witness;assert(context_store_registry_lab_admit_quarantine_v1(uh,s.credential,uh_evidence,uh_witness));std::array<uint8_t,1024>uh_output{};size_t uh_size=0;auto uh_result=context_store_registry_lab_encode_quarantine_v1(uh,s.credential,uh_witness,uh_output.data(),uh_output.size(),uh_size);auto exact_uh=quarantine_unattributable_head_for(s);assert(uh_result.authenticated()&&uh_size==exact_uh.size()&&std::equal(exact_uh.begin(),exact_uh.end(),uh_output.begin())&&uh_result.content_digest==dh("halofpx.registry-lab-quarantine.v1",exact_uh.data(),exact_uh.size()));
auto rejected_uh=uh_evidence;rejected_uh.standalone_predecessor_head_value=nullptr;context_store_registry_lab_quarantine_witness rejected_uh_witness;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
auto wrong_scope_head=head_predecessor_value;wrong_scope_head.scope.registry_epoch++;rejected_uh=uh_evidence;rejected_uh.standalone_predecessor_head_value=&wrong_scope_head;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
wrong_scope_head=head_predecessor_value;wrong_scope_head.scope.root_id[0]^=1;rejected_uh.standalone_predecessor_head_value=&wrong_scope_head;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));wrong_scope_head=head_predecessor_value;wrong_scope_head.scope.path_policy_commitment[0]^=1;rejected_uh.standalone_predecessor_head_value=&wrong_scope_head;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));wrong_scope_head=head_predecessor_value;wrong_scope_head.scope.registry_id.bytes[0]^=1;rejected_uh.standalone_predecessor_head_value=&wrong_scope_head;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
auto successor_descriptor=head_successor_value;successor_descriptor.expected_head_digest=uh.head_digest;rejected_uh=uh_evidence;rejected_uh.standalone_predecessor_head_value=&successor_descriptor;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
auto wrong_digest_head=head_predecessor_value;wrong_digest_head.expected_head_digest[0]^=1;rejected_uh=uh_evidence;rejected_uh.standalone_predecessor_head_value=&wrong_digest_head;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
auto wrong_descriptor=head_predecessor_value;wrong_descriptor.selected_envelope.bytes[0]^=1;rejected_uh.standalone_predecessor_head_value=&wrong_descriptor;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));wrong_descriptor=head_predecessor_value;wrong_descriptor.selected_envelope_digest[0]^=1;rejected_uh.standalone_predecessor_head_value=&wrong_descriptor;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));wrong_descriptor=head_predecessor_value;wrong_descriptor.selected_high_water++;rejected_uh.standalone_predecessor_head_value=&wrong_descriptor;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));wrong_descriptor=head_predecessor_value;wrong_descriptor.selector_generation++;rejected_uh.standalone_predecessor_head_value=&wrong_descriptor;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
rejected_uh=uh_evidence;rejected_uh.transition=&prepare_typed_value;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
rejected_uh=uh_evidence;rejected_uh.predecessor_head=nullptr;rejected_uh.predecessor_head_size=0;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
rejected_uh=uh_evidence;rejected_uh.predecessor_head=nullptr;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));rejected_uh=uh_evidence;rejected_uh.predecessor_head_size=0;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));rejected_uh=uh_evidence;rejected_uh.predecessor_head_size--;assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));auto corrupt_uh_head=golden_predecessor_head;corrupt_uh_head.back()^=1;rejected_uh=uh_evidence;rejected_uh.predecessor_head=corrupt_uh_head.data();assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));context_store_registry_lab_credential wrong_uh_credential;wrong_uh_credential.key_id=s.credential.key_id;wrong_uh_credential.generation=s.credential.generation;wrong_uh_credential.secret=s.credential.secret;wrong_uh_credential.secret[0]^=1;assert(!context_store_registry_lab_admit_quarantine_v1(uh,wrong_uh_credential,uh_evidence,rejected_uh_witness));
rejected_uh=uh_evidence;rejected_uh.successor_head=golden_successor_head.data();rejected_uh.successor_head_size=golden_successor_head.size();assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
rejected_uh=uh_evidence;rejected_uh.successor_head=golden_successor_head.data();assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));rejected_uh=uh_evidence;rejected_uh.successor_head_size=golden_successor_head.size();assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
rejected_uh=uh_evidence;rejected_uh.prepare=golden_prepare.data();rejected_uh.prepare_size=golden_prepare.size();assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
rejected_uh=uh_evidence;rejected_uh.prepare=golden_prepare.data();assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));rejected_uh=uh_evidence;rejected_uh.prepare_size=golden_prepare.size();assert(!context_store_registry_lab_admit_quarantine_v1(uh,s.credential,rejected_uh,rejected_uh_witness));
auto invalid_uh=uh;invalid_uh.attributable=true;assert(!context_store_registry_lab_admit_quarantine_v1(invalid_uh,s.credential,uh_evidence,rejected_uh_witness));invalid_uh=uh;invalid_uh.has_previous_record=true;invalid_uh.previous_record_digest=s.expect.prepare_digest;assert(!context_store_registry_lab_admit_quarantine_v1(invalid_uh,s.credential,uh_evidence,rejected_uh_witness));invalid_uh=uh;invalid_uh.phase=1;assert(!context_store_registry_lab_admit_quarantine_v1(invalid_uh,s.credential,uh_evidence,rejected_uh_witness));invalid_uh=uh;invalid_uh.phase=2;assert(!context_store_registry_lab_admit_quarantine_v1(invalid_uh,s.credential,uh_evidence,rejected_uh_witness));invalid_uh=uh;invalid_uh.has_head=false;invalid_uh.head_digest={};assert(!context_store_registry_lab_admit_quarantine_v1(invalid_uh,s.credential,uh_evidence,rejected_uh_witness));invalid_uh=uh;invalid_uh.attempt_id[0]=1;assert(!context_store_registry_lab_admit_quarantine_v1(invalid_uh,s.credential,uh_evidence,rejected_uh_witness));invalid_uh=uh;invalid_uh.slot=1;assert(!context_store_registry_lab_admit_quarantine_v1(invalid_uh,s.credential,uh_evidence,rejected_uh_witness));invalid_uh=uh;invalid_uh.operation_commitment[0]=1;assert(!context_store_registry_lab_admit_quarantine_v1(invalid_uh,s.credential,uh_evidence,rejected_uh_witness));
for(bool attributable:{false,true})for(bool previous:{false,true})for(bool readable_head:{false,true}){auto shaped=quarantine_value(s);shaped.attributable=attributable;shaped.has_previous_record=previous;shaped.has_head=readable_head;if(!attributable){shaped.attempt_id={};shaped.slot=0;shaped.operation_commitment={};}if(!previous)shaped.previous_record_digest={};if(!readable_head)shaped.head_digest={};context_store_registry_lab_quarantine_evidence_v1 shaped_evidence{};if(attributable||previous||readable_head)shaped_evidence.transition=&prepare_typed_value;if(attributable||previous){shaped_evidence.predecessor_head=golden_predecessor_head.data();shaped_evidence.predecessor_head_size=golden_predecessor_head.size();shaped_evidence.prepare=golden_prepare.data();shaped_evidence.prepare_size=golden_prepare.size();}if(readable_head){shaped_evidence.successor_head=golden_successor_head.data();shaped_evidence.successor_head_size=golden_successor_head.size();}context_store_registry_lab_quarantine_witness shaped_witness;bool admitted=context_store_registry_lab_admit_quarantine_v1(shaped,s.credential,shaped_evidence,shaped_witness);if(previous&&!attributable){assert(!admitted);continue;}assert(admitted);std::array<uint8_t,1024>shaped_output{};size_t shaped_size=0;assert(context_store_registry_lab_encode_quarantine_v1(shaped,s.credential,shaped_witness,shaped_output.data(),shaped_output.size(),shaped_size).authenticated());}
auto arbitrary_quarantine=quarantine_value(s);arbitrary_quarantine.previous_record_digest[0]^=1;context_store_registry_lab_quarantine_witness arbitrary_quarantine_witness;assert(!context_store_registry_lab_admit_quarantine_v1(arbitrary_quarantine,s.credential,quarantine_evidence,arbitrary_quarantine_witness));arbitrary_quarantine=quarantine_value(s);arbitrary_quarantine.head_digest[0]^=1;assert(!context_store_registry_lab_admit_quarantine_v1(arbitrary_quarantine,s.credential,quarantine_evidence,arbitrary_quarantine_witness));context_store_registry_lab_close_evidence_v1 missing_predecessor_close=close_evidence;missing_predecessor_close.predecessor_head=nullptr;missing_predecessor_close.predecessor_head_size=0;context_store_registry_lab_close_witness missing_predecessor_witness;assert(!context_store_registry_lab_admit_close_v1(close_value,s.credential,missing_predecessor_close,missing_predecessor_witness));
auto damaged_head=golden_predecessor_head;damaged_head[damaged_head.size()/2]^=1;context_store_registry_lab_root_evidence_v1 bad_evidence{damaged_head.data(),damaged_head.size()};context_store_registry_lab_root_witness rejected_witness;assert(!context_store_registry_lab_admit_root_v1(root_initialized_value,s.credential,bad_evidence,rejected_witness));
}
