#ifdef NDEBUG
#undef NDEBUG
#endif
#include "halofpx-context-store-registry-lab-wire.h"

#include <algorithm>
#include <array>
#include <cassert>
#include <cstdint>
#include <fstream>
#include <iterator>
#include <new>
#include <string>
#include <utility>
#include <vector>

using namespace halofpx;
namespace {
uint8_t nibble(char c){return uint8_t(c<='9'?c-'0':c-'a'+10);}
std::vector<uint8_t> hex_bytes(const std::string&s){assert(s.size()%2==0);std::vector<uint8_t>v(s.size()/2);for(size_t i=0;i<v.size();++i)v[i]=uint8_t(nibble(s[2*i])<<4|nibble(s[2*i+1]));return v;}
context_store_format_digest digest(const char*s){auto v=hex_bytes(s);assert(v.size()==32);context_store_format_digest d{};std::copy(v.begin(),v.end(),d.begin());return d;}
context_store_registered_id id(const char*s){context_store_registered_id x;while(s[x.size]){x.bytes[x.size]=s[x.size];++x.size;}return x;}
std::string value(const std::string&json,const std::string&key,size_t from=0){auto p=json.find("\""+key+"\"",from);assert(p!=std::string::npos);p=json.find(':',p)+1;p=json.find('"',p)+1;auto e=json.find('"',p);return json.substr(p,e-p);}
std::vector<uint8_t> fixture(const std::string&json,const char*name){auto p=json.find("\""+std::string(name)+"\"");assert(p!=std::string::npos);return hex_bytes(value(json,"envelope_hex",p));}
struct setup {
 std::array<uint8_t,32> secret{}; context_store_registry_lab_credential credential; context_store_registry_lab_expectation expect; std::array<uint8_t,1024> pred{},succ{};
 setup(uint64_t high=40,uint64_t delta=1){secret.fill(0x44);credential.key_id=id("registry-auth-v1");credential.generation=13;credential.secret=secret;context_store_protected_registry_key_record k{context_store_key_disposition::active,credential.key_id,13,{secret.data(),secret.size()}};context_store_protected_registry_body pb;pb.registry_id=id("registry-v1");pb.registry_epoch=9;pb.authority_base_scope_commitment.fill(0xaa);pb.policy_commitment.fill(0xbb);pb.last_consumed_sequence=high;auto pe=context_store_encode_protected_registry_v1(pb,k,pred.data(),pred.size());assert(pe.authenticated_carrier());context_store_protected_registry_successor_body sb;sb.registry_id=pb.registry_id;sb.registry_epoch=9;sb.authority_base_scope_commitment=pb.authority_base_scope_commitment;sb.policy_commitment=pb.policy_commitment;sb.consumed_authorization_high_water=high+delta;sb.predecessor_snapshot_envelope_digest=*pe.authenticated_carrier()->envelope_digest();sb.receipt.authorization_sequence=high+delta;sb.receipt.command_id.fill(0xcc);sb.receipt.authorization_token_digest.fill(0xdd);sb.receipt.plan_commitment.fill(0xee);sb.receipt.selected_manifest_digest.fill(0x11);sb.receipt.proposed_anchor_envelope_digest.fill(0x22);auto se=context_store_encode_protected_registry_successor_v1(sb,k,succ.data(),succ.size());assert(se.authenticated_carrier());expect.root_id.fill(0x11);expect.store_uuid.fill(0x22);expect.filesystem_uuid.fill(0x44);expect.registry_id=pb.registry_id;expect.registry_epoch=9;expect.predecessor_high_water=high;expect.predecessor_selector_generation=1;expect.successor_selector_generation=2;expect.mount_id=731;expect.owner_uid=1000;expect.lock_st_dev=2049;expect.lock_st_ino=987654;expect.path_policy_commitment=digest("162c7c9272841ccdec5dbf024d1d8dd511dbb4e2f538d8cdbab830e06abc9c0d");expect.initial_head_digest=digest("93ea1f031d4ec2827bc28535d56f2a0a1f6efb49ecff9ed763cf03bced0c0d82");expect.successor_head_digest=digest("d3d372ef42c5254a2baca52ba35cae46899cdf0e464396e3fa272ffc238a309b");expect.predecessor_envelope_digest=digest("5b6ea5887d96bf20c176e2346c2478149a8b7bcf1d84dc98843c28f4e00d0b9e");expect.successor_envelope_digest=digest("ee621ab3efa4c76cc2e2132034a404d6a373701ad8772f0576fd5bd20087c5cd");expect.prepare_digest=digest("9ea5eced3354b6a90ca306361568de879d5ebfc9effd63de6f73629c04baa8fa");expect.operation_commitment=digest("f28cb18e21d74d63346bddacbd482e28a55989cfa2f9e18cea382792a89b7fb1");expect.attempt_id.fill(0x66);expect.quarantine_event_id.fill(0x77);expect.quarantine_attributable=true;expect.quarantine_has_previous_record=true;expect.quarantine_previous_record_digest=expect.prepare_digest;expect.quarantine_has_head=true;expect.quarantine_head_digest=expect.successor_head_digest;expect.quarantine_reason=6;expect.quarantine_phase=2;expect.slot=17;expect.predecessor=pred.data();expect.predecessor_size=pe.encoded_size;expect.successor=succ.data();expect.successor_size=se.encoded_size;}
};
using bytes=std::vector<uint8_t>;
bytes u(uint64_t v){bytes x;if(v<24)x.push_back(uint8_t(v));else if(v<=255)x={0x18,uint8_t(v)};else if(v<=65535)x={0x19,uint8_t(v>>8),uint8_t(v)};else{x={0x1a,uint8_t(v>>24),uint8_t(v>>16),uint8_t(v>>8),uint8_t(v)};}return x;}
bytes bs(const uint8_t*p,size_t n){auto h=u(n);h[0]|=0x40;h.insert(h.end(),p,p+n);return h;}template<size_t N>bytes bs(const std::array<uint8_t,N>&x){return bs(x.data(),x.size());}
bytes ts(const context_store_registered_id&i){auto h=u(i.size);h[0]|=0x60;h.insert(h.end(),i.bytes.begin(),i.bytes.begin()+i.size);return h;}
bytes mp(std::initializer_list<std::pair<uint64_t,bytes>>items){bytes out=u(items.size());out[0]|=0xa0;for(const auto&x:items){auto k=u(x.first);out.insert(out.end(),k.begin(),k.end());out.insert(out.end(),x.second.begin(),x.second.end());}return out;}
context_store_format_digest dh(const char*domain,const uint8_t*p,size_t n){bytes x(domain,domain+std::char_traits<char>::length(domain)+1);x.insert(x.end(),p,p+n);context_store_format_digest d{};assert(context_store_sha256_bounded(x.data(),x.size(),x.size(),d));return d;}
context_store_format_digest op_digest(const setup&s){auto body=mp({{0,bs(s.expect.root_id)},{1,bs(s.expect.path_policy_commitment)},{2,bs(s.expect.attempt_id)},{3,u(s.expect.slot)},{4,bs(s.expect.predecessor_envelope_digest)},{5,bs(s.expect.successor_envelope_digest)},{6,u(s.expect.predecessor_size)},{7,u(s.expect.successor_size)}});return dh("halofpx.registry-lab-operation.v1",body.data(),body.size());}
void refresh(setup&s){s.expect.predecessor_envelope_digest=dh("halofpx.registry-lab-registry-envelope.v1",s.pred.data(),s.expect.predecessor_size);s.expect.successor_envelope_digest=dh("halofpx.registry-lab-registry-envelope.v1",s.succ.data(),s.expect.successor_size);s.expect.operation_commitment=op_digest(s);}
bytes auth(const bytes&body,const setup&s,const char*domain){auto input=mp({{0,body},{1,ts(s.credential.key_id)},{2,u(1)},{3,u(s.credential.generation)}});context_store_format_digest dk{},tag{};constexpr char key_domain[]="halofpx.registry-lab-key.v1";bytes kd(reinterpret_cast<const uint8_t*>(key_domain),reinterpret_cast<const uint8_t*>(key_domain)+sizeof(key_domain));auto kid=ts(s.credential.key_id);kd.insert(kd.end(),kid.begin(),kid.end());auto gen=u(s.credential.generation);kd.insert(kd.end(),gen.begin(),gen.end());assert(context_store_hmac_sha256(s.secret.data(),32,kd.data(),kd.size(),dk));bytes msg(reinterpret_cast<const uint8_t*>(domain),reinterpret_cast<const uint8_t*>(domain)+std::char_traits<char>::length(domain)+1);msg.insert(msg.end(),input.begin(),input.end());assert(context_store_hmac_sha256(dk.data(),32,msg.data(),msg.size(),tag));return mp({{0,input},{1,bs(tag)}});}
bytes head_for(const setup&s,bool successor,uint64_t generation){auto*d=successor?&s.expect.successor_envelope_digest:&s.expect.predecessor_envelope_digest;size_t z=successor?s.expect.successor_size:s.expect.predecessor_size;auto body=mp({{0,u(1)},{1,u(0)},{2,u(1)},{3,bs(s.expect.root_id)},{4,bs(s.expect.path_policy_commitment)},{5,bs(*d)},{6,u(z)},{7,ts(s.expect.registry_id)},{8,u(s.expect.registry_epoch)},{9,u(s.expect.predecessor_high_water+(successor?1:0))},{10,u(generation)},{11,ts(s.credential.key_id)},{12,u(s.credential.generation)}});return auth(body,s,"halofpx.registry-lab-head-auth.v1");}
bytes prepare_for(const setup&s){auto body=mp({{0,u(1)},{1,u(0)},{2,u(2)},{3,bs(s.expect.root_id)},{4,bs(s.expect.path_policy_commitment)},{5,bs(s.expect.attempt_id)},{6,u(s.expect.slot)},{7,bs(s.expect.operation_commitment)},{8,u(s.expect.predecessor_size)},{9,bs(s.pred.data(),s.expect.predecessor_size)},{10,bs(s.expect.predecessor_envelope_digest)},{11,u(s.expect.successor_size)},{12,bs(s.succ.data(),s.expect.successor_size)},{13,bs(s.expect.successor_envelope_digest)},{14,u(1)},{15,bs(s.expect.initial_head_digest)},{16,bs(s.expect.initial_head_digest)}});return auth(body,s,"halofpx.registry-lab-prepare-auth.v1");}
bytes quarantine_unattributable_for(const setup&s){bytes nullv{0xf6};auto body=mp({{0,u(1)},{1,u(0)},{2,u(5)},{3,bs(s.expect.root_id)},{4,bs(s.expect.path_policy_commitment)},{5,bs(s.expect.quarantine_event_id)},{6,nullv},{7,nullv},{8,u(s.expect.quarantine_reason)},{9,u(s.expect.quarantine_phase)},{10,nullv},{11,nullv},{12,nullv}});return auth(body,s,"halofpx.registry-lab-quarantine-auth.v1");}
void retag(std::vector<uint8_t>&v,const setup&s,const char*domain){context_store_format_digest dk{},tag{};std::array<uint8_t,256>kdf{};size_t n=0;auto put=[&](const void*p,size_t z){std::copy_n(static_cast<const uint8_t*>(p),z,kdf.begin()+n);n+=z;};constexpr char kd[]="halofpx.registry-lab-key.v1";put(kd,sizeof(kd));uint8_t t=0x70;put(&t,1);put(s.credential.key_id.bytes.data(),16);uint8_t g=13;put(&g,1);assert(context_store_hmac_sha256(s.secret.data(),32,kdf.data(),n,dk));std::vector<uint8_t>msg;msg.insert(msg.end(),domain,domain+std::char_traits<char>::length(domain)+1);msg.insert(msg.end(),v.begin()+2,v.end()-35);assert(context_store_hmac_sha256(dk.data(),32,msg.data(),msg.size(),tag));std::copy(tag.begin(),tag.end(),v.end()-32);}
bool replace(std::vector<uint8_t>&v,std::initializer_list<uint8_t>from,std::initializer_list<uint8_t>to){auto p=std::search(v.begin(),v.end(),from.begin(),from.end());if(p==v.end())return false;auto at=size_t(p-v.begin());v.erase(v.begin()+at,v.begin()+at+from.size());v.insert(v.begin()+at,to.begin(),to.end());return true;}
}
int main(int argc,char**argv){assert(argc==2);std::ifstream f(argv[1],std::ios::binary);std::string json((std::istreambuf_iterator<char>(f)),{});setup s;
auto package=hex_bytes(value(json,"credential_package_hex"));context_store_registry_lab_credential parsed;assert(context_store_registry_lab_parse_credential_v1(package.data(),package.size(),parsed));assert(parsed.generation==13&&parsed.key_id.size==16&&parsed.secret==s.secret);context_store_registry_lab_credential moved(std::move(parsed));assert(parsed.generation==0&&!std::any_of(parsed.secret.begin(),parsed.secret.end(),[](uint8_t b){return b!=0;}));assert(moved.generation==13&&moved.secret==s.secret);parsed=std::move(moved);for(size_t i=0;i<package.size();++i){auto x=package;x[i]^=1;context_store_registry_lab_credential ignored;assert(!context_store_registry_lab_parse_credential_v1(x.data(),x.size(),ignored)||ignored.secret!=s.secret||ignored.generation!=13||!std::equal(ignored.key_id.bytes.begin(),ignored.key_id.bytes.begin()+ignored.key_id.size,s.credential.key_id.bytes.begin(),s.credential.key_id.bytes.begin()+s.credential.key_id.size));}
context_store_registry_lab_credential seeded;seeded.key_id=id("seeded");seeded.generation=99;seeded.secret.fill(0xaa);assert(!context_store_registry_lab_parse_credential_v1(nullptr,0,seeded));assert(!seeded.generation&&!seeded.key_id.size&&!std::any_of(seeded.secret.begin(),seeded.secret.end(),[](uint8_t b){return b!=0;}));
alignas(context_store_registry_lab_credential) std::array<std::byte,sizeof(context_store_registry_lab_credential)> storage{};auto*placed=new(storage.data()) context_store_registry_lab_credential;placed->key_id=id("placed");placed->generation=7;placed->secret.fill(0x5a);auto*secret_address=placed->secret.data();placed->~context_store_registry_lab_credential();assert(std::all_of(secret_address,secret_address+32,[](uint8_t b){return b==0;}));
std::array<uint8_t,16>fs{},sub{};fs.fill(0x44);sub.fill(0x45);context_store_format_digest path{};const std::string parent="/mnt/halofpx-l05o-loop",root=parent+"/run-001";assert(context_store_registry_lab_path_policy_v1((const uint8_t*)parent.data(),parent.size(),(const uint8_t*)root.data(),root.size(),fs,sub,731,2049,1000,path));assert(path==s.expect.path_policy_commitment);
struct row{const char*name;context_store_registry_lab_kind kind;const char*digest_hex;};const row rows[]={
{"root_initializing",context_store_registry_lab_kind::root,"902e919dd48e0f0ceece0156f09806edd46d8e68a4c2eab7c34225334c2f9fa8"},{"root_initialized",context_store_registry_lab_kind::root,"6ce909a8b9985fcaf152ecd1c6ffb7fa9217041928f116bc01409d72e60ae39c"},{"head_initial",context_store_registry_lab_kind::head,"93ea1f031d4ec2827bc28535d56f2a0a1f6efb49ecff9ed763cf03bced0c0d82"},{"prepare",context_store_registry_lab_kind::prepare,"9ea5eced3354b6a90ca306361568de879d5ebfc9effd63de6f73629c04baa8fa"},{"head_successor",context_store_registry_lab_kind::head,"d3d372ef42c5254a2baca52ba35cae46899cdf0e464396e3fa272ffc238a309b"},{"close",context_store_registry_lab_kind::close,"526e0025c5b5833fc2d731473ca6db3175dc25edc37996f60827a4f65151a1e8"},{"abort",context_store_registry_lab_kind::abort_record,"42a0a0890bd0a861b8046a8f4fd9b579fcba2bc8aefbd0c1973b3197a522f70b"},{"quarantine",context_store_registry_lab_kind::quarantine,"c77c94ec11040a9379533dbd8c74ba3bf50ff3436e34d2a593c0f2f3106e21a4"}};
for(const auto&r:rows){auto v=fixture(json,r.name);auto good=context_store_registry_lab_verify_v1(r.kind,v.data(),v.size(),s.credential,s.expect);assert(good.authenticated()&&good.content_digest==digest(r.digest_hex));for(size_t cut=0;cut<v.size();++cut)assert(!context_store_registry_lab_verify_v1(r.kind,v.data(),cut,s.credential,s.expect).authenticated());for(size_t i=0;i<v.size();++i){auto x=v;x[i]^=1;assert(!context_store_registry_lab_verify_v1(r.kind,x.data(),x.size(),s.credential,s.expect).authenticated());}auto trailing=v;trailing.push_back(0);assert(!context_store_registry_lab_verify_v1(r.kind,trailing.data(),trailing.size(),s.credential,s.expect).authenticated());}
auto root_only=s.expect;root_only.predecessor=nullptr;root_only.predecessor_size=0;root_only.successor=nullptr;root_only.successor_size=0;root_only.predecessor_envelope_digest={};root_only.successor_envelope_digest={};root_only.prepare_digest={};root_only.operation_commitment={};root_only.attempt_id={};root_only.quarantine_event_id={};root_only.initial_head_digest={};auto initializing=fixture(json,"root_initializing");assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::root,initializing.data(),initializing.size(),s.credential,root_only).authenticated());
auto head_only=s.expect;head_only.successor=nullptr;head_only.successor_size=0;head_only.successor_envelope_digest={};head_only.successor_selector_generation=0;head_only.prepare_digest={};head_only.operation_commitment={};head_only.attempt_id={};head_only.quarantine_event_id={};auto initial=fixture(json,"head_initial");assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,initial.data(),initial.size(),s.credential,head_only).authenticated());
for(auto field:std::array<int,3>{0,1,2}){auto zero=fixture(json,"root_initializing");bool changed=field==0?replace(zero,{0x08,0x19,0x02,0xdb},{0x08,0x00}):field==1?replace(zero,{0x10,0x19,0x08,0x01},{0x10,0x00}):replace(zero,{0x11,0x1a,0x00,0x0f,0x12,0x06},{0x11,0x00});assert(changed);retag(zero,s,"halofpx.registry-lab-root-auth.v1");auto expected=s.expect;if(field==0)expected.mount_id=0;else if(field==1)expected.lock_st_dev=0;else expected.lock_st_ino=0;assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::root,zero.data(),zero.size(),s.credential,expected).authenticated());}
auto head=fixture(json,"head_initial");const std::array<uint8_t,2> selector_generation={0x0a,0x01};auto p=std::search(head.begin(),head.end(),selector_generation.begin(),selector_generation.end());assert(p!=head.end());p[1]=3;retag(head,s,"halofpx.registry-lab-head-auth.v1");auto alternate=s.expect;alternate.predecessor_selector_generation=3;alternate.successor_selector_generation=4;assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,head.data(),head.size(),s.credential,alternate).authenticated());
auto invalid=s.expect;invalid.predecessor_size=0;assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,head.data(),head.size(),s.credential,invalid).authenticated());invalid=s.expect;invalid.registry_id={};assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,head.data(),head.size(),s.credential,invalid).authenticated());
auto wrong=s.expect;wrong.path_policy_commitment[0]^=1;auto q=fixture(json,"quarantine");assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,q.data(),q.size(),s.credential,wrong).authenticated());
auto qreason=q;assert(replace(qreason,{0x08,0x06,0x09,0x02},{0x08,0x07,0x09,0x02}));retag(qreason,s,"halofpx.registry-lab-quarantine-auth.v1");assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,qreason.data(),qreason.size(),s.credential,s.expect).authenticated());auto qexpect=s.expect;qexpect.quarantine_reason=7;assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,qreason.data(),qreason.size(),s.credential,qexpect).authenticated());
auto close=fixture(json,"close");assert(replace(close,{0x0b,0x02,0x0c,0x00},{0x0b,0x01,0x0c,0x00}));retag(close,s,"halofpx.registry-lab-close-auth.v1");assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::close,close.data(),close.size(),s.credential,s.expect).authenticated());
auto recovery=fixture(json,"close");assert(replace(recovery,{0x0b,0x02,0x0c,0x00},{0x0b,0x02,0x0c,0x01}));retag(recovery,s,"halofpx.registry-lab-close-auth.v1");assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::close,recovery.data(),recovery.size(),s.credential,s.expect).authenticated());
setup arbitrary(123);refresh(arbitrary);arbitrary.expect.predecessor_selector_generation=7;arbitrary.expect.successor_selector_generation=8;auto arbitrary_head=head_for(arbitrary,false,7);assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,arbitrary_head.data(),arbitrary_head.size(),arbitrary.credential,arbitrary.expect).authenticated());auto arbitrary_successor=head_for(arbitrary,true,8);assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,arbitrary_successor.data(),arbitrary_successor.size(),arbitrary.credential,arbitrary.expect).authenticated());
assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::head,arbitrary_head.data(),arbitrary_head.size(),s.credential,s.expect).authenticated());
setup skipped(40,2);refresh(skipped);auto repaired_h_plus_two=prepare_for(skipped);assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::prepare,repaired_h_plus_two.data(),repaired_h_plus_two.size(),skipped.credential,skipped.expect).authenticated());
setup wrong_operation;refresh(wrong_operation);wrong_operation.expect.operation_commitment[0]^=1;auto repaired_wrong_operation=prepare_for(wrong_operation);assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::prepare,repaired_wrong_operation.data(),repaired_wrong_operation.size(),wrong_operation.credential,wrong_operation.expect).authenticated());
setup unattributable;unattributable.expect.quarantine_attributable=false;unattributable.expect.quarantine_has_previous_record=false;unattributable.expect.quarantine_has_head=false;auto qnull=quarantine_unattributable_for(unattributable);assert(context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,qnull.data(),qnull.size(),unattributable.credential,unattributable.expect).authenticated());assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,q.data(),q.size(),unattributable.credential,unattributable.expect).authenticated());assert(!context_store_registry_lab_verify_v1(context_store_registry_lab_kind::quarantine,qnull.data(),qnull.size(),s.credential,s.expect).authenticated());
}
