set(TARGET rpc-server)
add_executable(${TARGET} rpc-server.cpp)
target_link_libraries(${TARGET} PRIVATE ggml)
target_compile_features(${TARGET} PRIVATE cxx_std_17)
if (GGML_RPC_HALOFPX_LOCAL_STATE)
    target_compile_definitions(${TARGET} PRIVATE GGML_RPC_HALOFPX_LOCAL_STATE=1)
endif()

if(LLAMA_TOOLS_INSTALL)
    install(TARGETS ${TARGET} RUNTIME)
endif()
