function(halofpx_registry_lab_write_reachable_graph OUTPUT_PATH)
    set(ROOT_TARGETS ${ARGN})
    file(WRITE "${OUTPUT_PATH}" "# complete configure-time reachable CMake target graph\n")
    foreach(ROOT_TARGET IN LISTS ROOT_TARGETS)
        if(NOT TARGET ${ROOT_TARGET})
            message(FATAL_ERROR "missing L05o graph-audit root: ${ROOT_TARGET}")
        endif()
        set(GRAPH_QUEUE "${ROOT_TARGET}")
        set(GRAPH_VISITED "")
        while(GRAPH_QUEUE)
            list(GET GRAPH_QUEUE 0 GRAPH_FROM)
            list(REMOVE_AT GRAPH_QUEUE 0)
            if(GRAPH_FROM IN_LIST GRAPH_VISITED)
                continue()
            endif()
            list(APPEND GRAPH_VISITED "${GRAPH_FROM}")
            file(APPEND "${OUTPUT_PATH}" "target|${ROOT_TARGET}|${GRAPH_FROM}\n")
            get_target_property(GRAPH_LINKS ${GRAPH_FROM} LINK_LIBRARIES)
            get_target_property(GRAPH_INTERFACE ${GRAPH_FROM} INTERFACE_LINK_LIBRARIES)
            foreach(GRAPH_PROPERTY IN ITEMS GRAPH_LINKS GRAPH_INTERFACE)
                if("${${GRAPH_PROPERTY}}" STREQUAL "${GRAPH_PROPERTY}-NOTFOUND")
                    set(${GRAPH_PROPERTY} "")
                endif()
            endforeach()
            set(GRAPH_ITEMS ${GRAPH_LINKS} ${GRAPH_INTERFACE})
            foreach(GRAPH_TO IN LISTS GRAPH_ITEMS)
                string(REGEX REPLACE "^\\$<LINK_ONLY:([^>]+)>$" "\\1" GRAPH_TO "${GRAPH_TO}")
                string(REGEX REPLACE "^\\$<BUILD_INTERFACE:([^>]+)>$" "\\1" GRAPH_TO "${GRAPH_TO}")
                if(TARGET ${GRAPH_TO})
                    file(APPEND "${OUTPUT_PATH}" "edge|${ROOT_TARGET}|${GRAPH_FROM}|${GRAPH_TO}\n")
                    if(NOT GRAPH_TO IN_LIST GRAPH_VISITED)
                        list(APPEND GRAPH_QUEUE "${GRAPH_TO}")
                    endif()
                elseif(NOT GRAPH_TO STREQUAL "")
                    string(REPLACE "|" "<PIPE>" GRAPH_RAW "${GRAPH_TO}")
                    file(APPEND "${OUTPUT_PATH}" "raw|${ROOT_TARGET}|${GRAPH_FROM}|${GRAPH_RAW}\n")
                endif()
            endforeach()
        endwhile()
    endforeach()
endfunction()
