if (HALOFPX_REGISTRY_LAB_LINUX_MUTATION)
    message(FATAL_ERROR
        "HALOFPX_REGISTRY_LAB_LINUX_MUTATION is not admitted by ADR-0025")
endif()

if (HALOFPX_REGISTRY_LAB_LINUX_PREINIT AND
    NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR
        "HALOFPX_REGISTRY_LAB_LINUX_PREINIT is available only on Linux")
endif()

if (HALOFPX_REGISTRY_LAB_LINUX_INITIALIZER AND
    NOT HALOFPX_REGISTRY_LAB_LINUX_PREINIT)
    message(FATAL_ERROR
        "HALOFPX_REGISTRY_LAB_LINUX_INITIALIZER requires HALOFPX_REGISTRY_LAB_LINUX_PREINIT")
endif()

if (HALOFPX_REGISTRY_LAB_LINUX_INITIALIZER AND
    NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR
        "HALOFPX_REGISTRY_LAB_LINUX_INITIALIZER is available only on Linux")
endif()
